MORE_TRUTHS = [
    'Have you ever cried because of your ex?',
    'Have you ever judged your teacher?',
    'Have you ever stalked the social media of your sibling?',
    'What is the weirdest thing you ever asked the person sitting next to you?',
    'Have you ever forgotten the birthday of your past self?',
    'Have you ever judged a random person on the street?',
    'Have you ever given fake advice to your gym trainer?',
    'Have you ever stolen something from your favorite musician?',
    'What is a guilty pleasure you share with your worst enemy?',
    'Have you ever been jealous of your future self?',
    'Have you ever tried to impress a random person on the street?',
    'Have you ever snooped through the phone of your local barista?',
    'What is the biggest lie you ever told your childhood hero?',
    'Have you ever cried because of your boss?',
    'What is the weirdest thing you ever asked someone you follow on Instagram?',
    'Have you ever forgotten the birthday of your high school principal?',
    'What is a habit you find annoying about the funniest person you know?',
    'Have you ever been jealous of your sibling?',
    "What is the strangest dream you've had involving your secret admirer?",
    'What would you do if you were stuck in an elevator with your neighbor?',
    'Have you ever accidentally sent a text meant for someone else to your pet?',
    'Have you ever been jealous of someone you follow on Instagram?',
    'Have you ever been jealous of the last person you texted?',
    'What is your honest opinion of the last person you texted?',
    "What is the worst thing you've ever said behind the back of a random Discord user?",
    'If you had to trade lives with a Twitch streamer?',
    'Have you ever lied to get out of hanging out with your online friend?',
    'What is a secret you are keeping from your ex?',
    'Have you ever lied to get out of hanging out with your ex?',
    'Have you ever stalked the social media of your pet?',
    'What would you do if you were stuck in an elevator with a politician?',
    "What is the weirdest thought you've had about your online friend?",
    "What is the strangest dream you've had involving a celebrity?",
    "What is the most embarrassing thing you've ever done in front of your future self?",
    'Have you ever stolen something from your pet?',
    "What is the worst thing you've ever said behind the back of your favorite actor?",
    'What is a habit you find annoying about your childhood hero?',
    'Have you ever given fake advice to your high school principal?',
    "What is the worst thing you've ever said behind the back of your favorite musician?",
    'Have you ever tried to impress your future self?',
    'Have you ever stalked the social media of a fictional character?',
    "What is the most awkward interaction you've had with your boss?",
    'What is a rumor you heard about a delivery driver?',
    'What is a habit you find annoying about someone you follow on Instagram?',
    'Have you ever ignored a call from a ghost?',
    'Have you ever pretended to like a gift from your childhood hero?',
    'Have you ever given fake advice to a fictional character?',
    'Have you ever cried because of the last person you texted?',
    "What is the strangest dream you've had involving your worst enemy?",
    'What is a guilty pleasure you share with a random person on the street?',
    'What is the funniest memory you have of your cousin?',
    'Have you ever snooped through the phone of a Twitch streamer?',
    "What is the worst thing you've ever said behind the back of your crush?",
    'What is the funniest memory you have of your favorite actor?',
    'Have you ever ignored a call from a fictional character?',
    'Have you ever tried to impress a politician?',
    'Have you ever cried because of your worst enemy?',
    'Have you ever judged a Twitch streamer?',
    "What is the weirdest thought you've had about your best friend?",
    'Have you ever ignored a call from your sibling?',
    'What is the funniest memory you have of the last person you texted?',
    'Have you ever lied to get out of hanging out with a politician?',
    'If you had to trade lives with the person sitting next to you?',
    "What is the strangest dream you've had involving your boss?",
    'What is the biggest lie you ever told the server owner?',
    'Have you ever cried because of your favorite actor?',
    'Have you ever had a crush on your high school principal?',
    'What is a rumor you heard about your teacher?',
    'Have you ever had a crush on your cousin?',
    'Have you ever accidentally sent a text meant for someone else to your future self?',
    'If you had to trade lives with your local barista?',
    'What is the biggest lie you ever told your gym trainer?',
    'What is a guilty pleasure you share with your crush?',
    'What is the meanest thing you ever did to a politician?',
    'Have you ever stalked the social media of your online friend?',
    'Have you ever accidentally sent a text meant for someone else to your high school principal?',
    'Have you ever given fake advice to a politician?',
    'What is a secret you are keeping from the funniest person you know?',
    'If you had to trade lives with your best friend?',
    'Have you ever had a crush on a random person on the street?',
    "What is the strangest dream you've had involving your teacher?",
    "What is the worst thing you've ever said behind the back of your online friend?",
    'Have you ever snooped through the phone of a ghost?',
    'Have you ever tried to impress a delivery driver?',
    'What is your honest opinion of your reflection?',
    "What is the weirdest thought you've had about a random Discord user?",
    'Have you ever given fake advice to your worst enemy?',
    "What is the most awkward interaction you've had with your ex?",
    'Have you ever stalked the social media of your first love?',
    'What is a rumor you heard about a politician?',
    'Have you ever lied to get out of hanging out with your neighbor?',
    'What is the weirdest thing you ever asked your neighbor?',
    'What is a habit you find annoying about a stranger?',
    'What is the biggest lie you ever told your local barista?',
    'If you had to trade lives with your boss?',
    'Have you ever stalked the social media of your gym trainer?',
    'What is the funniest memory you have of a celebrity?',
    'Have you ever stolen something from your secret admirer?',
    'What is a secret you are keeping from a fictional character?',
    "What is the most embarrassing thing you've ever done in front of your worst enemy?",
    'What is a guilty pleasure you share with a celebrity?',
    'What would you do if you were stuck in an elevator with your childhood hero?',
    'What is a rumor you heard about your past self?',
    'What is a rumor you heard about your doctor?',
    'Have you ever judged a fictional character?',
    'What is your honest opinion of your boss?',
    'What is the meanest thing you ever did to the person sitting next to you?',
    'Have you ever stolen something from your reflection?',
    'Have you ever ignored a call from your cousin?',
    'Have you ever forgotten the birthday of the person sitting next to you?',
    'Have you ever ignored a call from your pet?',
    'Have you ever accidentally sent a text meant for someone else to a YouTuber?',
    'Have you ever judged the person sitting next to you?',
    'What is a guilty pleasure you share with your childhood hero?',
    'What is a secret you are keeping from a ghost?',
    'Have you ever been jealous of a stranger?',
    'If you had to trade lives with your reflection?',
    'What is the biggest lie you ever told your cousin?',
    "What is the weirdest thought you've had about your local barista?",
    'Have you ever ignored a call from your boss?',
    'What is a secret you are keeping from the server owner?',
    'If you had to trade lives with your childhood hero?',
    'Have you ever ignored a call from a YouTuber?',
    'What is a habit you find annoying about a fictional character?',
    'Have you ever stolen something from a celebrity?',
    "What is the most embarrassing thing you've ever done in front of someone you follow on Instagram?",
    'Have you ever pretended to like a gift from your sibling?',
    'What would you do if you were stuck in an elevator with your online friend?',
    'Have you ever had a crush on a YouTuber?',
    'Have you ever forgotten the birthday of your best friend?',
    'Have you ever pretended to like a gift from a YouTuber?',
    'Have you ever tried to impress your reflection?',
    'What is a habit you find annoying about your worst enemy?',
    'Have you ever judged your worst enemy?',
    'What is the funniest memory you have of a delivery driver?',
    'Have you ever been jealous of your grandfather?',
    'What is the biggest lie you ever told a delivery driver?',
    "What is the weirdest thought you've had about the server owner?",
    'What is a secret you are keeping from your neighbor?',
    'What is your honest opinion of your pet?',
    'What is the funniest memory you have of your future self?',
    "What is the most embarrassing thing you've ever done in front of the person sitting next to you?",
    "What is the most awkward interaction you've had with your doctor?",
    'What is a guilty pleasure you share with a delivery driver?',
    'What is a secret you are keeping from your secret admirer?',
    "What is the most awkward interaction you've had with your childhood hero?",
    'Have you ever stolen something from the last person you texted?',
    'What is the weirdest thing you ever asked your worst enemy?',
    'What is the meanest thing you ever did to your secret admirer?',
    'What is the meanest thing you ever did to your online friend?',
    'Have you ever been jealous of your pet?',
    'What is the biggest lie you ever told your ex?',
    'If you had to trade lives with your neighbor?',
    'Have you ever been jealous of a politician?',
    'What is your honest opinion of your local barista?',
    'What is a rumor you heard about the person sitting next to you?',
    'Have you ever cried because of your high school principal?',
    'Have you ever accidentally sent a text meant for someone else to your online friend?',
    "What is the most awkward interaction you've had with a politician?",
    'Have you ever pretended to like a gift from a politician?',
    'What is a habit you find annoying about your future self?',
    'Have you ever accidentally sent a text meant for someone else to your gym trainer?',
    'What is the funniest memory you have of a fictional character?',
    'Have you ever given fake advice to the funniest person you know?',
    'What is a habit you find annoying about your doctor?',
    'Have you ever snooped through the phone of your future self?',
    'What would you do if you were stuck in an elevator with your high school principal?',
    'Have you ever ignored a call from a politician?',
    'Have you ever ignored a call from your crush?',
    'Have you ever stalked the social media of your boss?',
    'What is a habit you find annoying about your favorite actor?',
    'Have you ever been jealous of your worst enemy?',
    'If you had to trade lives with a celebrity?',
    'What is a rumor you heard about your pet?',
    'Have you ever snooped through the phone of your ex?',
    "What is the weirdest thought you've had about your grandfather?",
    'Have you ever forgotten the birthday of a Twitch streamer?',
    'What is a secret you are keeping from a celebrity?',
    "What is the most awkward interaction you've had with your best friend?",
    'Have you ever stalked the social media of a random person on the street?',
    "What is the worst thing you've ever said behind the back of someone you follow on Instagram?",
    'What is your honest opinion of your doctor?',
    "What is the strangest dream you've had involving a politician?",
    'What is the weirdest thing you ever asked your sibling?',
    "What is the most embarrassing thing you've ever done in front of your ex?",
    'Have you ever snooped through the phone of your worst enemy?',
    'Have you ever ignored a call from your childhood hero?',
    'What is a habit you find annoying about your secret admirer?',
    'Have you ever lied to get out of hanging out with your reflection?',
    'What is a habit you find annoying about a celebrity?',
    'Have you ever snooped through the phone of your doctor?',
    'What is the meanest thing you ever did to your favorite musician?',
    'Have you ever tried to impress your local barista?',
    'Have you ever ignored a call from your ex?',
    'Have you ever stolen something from your teacher?',
    'What is a secret you are keeping from your best friend?',
    'Have you ever stolen something from your high school principal?',
    'Have you ever lied to get out of hanging out with your gym trainer?',
    'What is a guilty pleasure you share with your reflection?',
    'What is the weirdest thing you ever asked your ex?',
    'Have you ever snooped through the phone of someone you follow on Instagram?',
    'Have you ever stolen something from your doctor?',
    "What is the strangest dream you've had involving a fictional character?",
    'If you had to trade lives with your crush?',
    'What is a rumor you heard about a stranger?',
    'What is a guilty pleasure you share with your favorite actor?',
    "What is the strangest dream you've had involving a Twitch streamer?",
    'Have you ever accidentally sent a text meant for someone else to a stranger?',
    'Have you ever lied to get out of hanging out with a stranger?',
    'Have you ever tried to impress the last person you texted?',
    'What is the weirdest thing you ever asked your boss?',
    'Have you ever cried because of your local barista?',
    'Have you ever tried to impress the smartest person you know?',
    "What is the worst thing you've ever said behind the back of your gym trainer?",
    'What is the weirdest thing you ever asked your doctor?',
    'What is a rumor you heard about your cousin?',
    'What is a rumor you heard about the server owner?',
    'Have you ever stolen something from the person sitting next to you?',
    'Have you ever pretended to like a gift from a fictional character?',
    'Have you ever stalked the social media of your local barista?',
    'What is the funniest memory you have of your childhood hero?',
    'Have you ever tried to impress someone you follow on Instagram?',
    "What is the strangest dream you've had involving your doctor?",
    'What is your honest opinion of a stranger?',
    'What is a rumor you heard about your worst enemy?',
    'What is the funniest memory you have of the funniest person you know?',
    'Have you ever stalked the social media of a stranger?',
    'Have you ever lied to get out of hanging out with your high school principal?',
    'Have you ever had a crush on your doctor?',
    'Have you ever pretended to like a gift from your first love?',
    'What is the weirdest thing you ever asked the smartest person you know?',
    'Have you ever forgotten the birthday of a fictional character?',
    'What is a guilty pleasure you share with your favorite musician?',
    "What is the most embarrassing thing you've ever done in front of your high school principal?",
    'What is a guilty pleasure you share with a YouTuber?',
    'What is a guilty pleasure you share with your pet?',
    'Have you ever stalked the social media of your favorite musician?',
    'If you had to trade lives with your past self?',
    'Have you ever accidentally sent a text meant for someone else to your doctor?',
    'What is the weirdest thing you ever asked a celebrity?',
    "What is the worst thing you've ever said behind the back of the server owner?",
    'Have you ever lied to get out of hanging out with your crush?',
    'What is the biggest lie you ever told your online friend?',
    'Have you ever accidentally sent a text meant for someone else to your cousin?',
    'What is a rumor you heard about your future self?',
    'What is the meanest thing you ever did to your doctor?',
    'Have you ever stalked the social media of your grandfather?',
    'Have you ever judged your high school principal?',
    'What is the funniest memory you have of your grandfather?',
    'What is the weirdest thing you ever asked a YouTuber?',
    'Have you ever snooped through the phone of your cousin?',
    'What is a secret you are keeping from your high school principal?',
    'What is the funniest memory you have of your worst enemy?',
    'What is a guilty pleasure you share with your high school principal?',
    'Have you ever pretended to like a gift from the funniest person you know?',
    'Have you ever tried to impress a YouTuber?',
    "What is the weirdest thought you've had about a random person on the street?",
    'Have you ever stolen something from the server owner?',
    "What is the most embarrassing thing you've ever done in front of your childhood hero?",
    "What is the worst thing you've ever said behind the back of your future self?",
    'Have you ever stolen something from your best friend?',
    'Have you ever tried to impress your past self?',
    'What is a guilty pleasure you share with the person sitting next to you?',
    'Have you ever tried to impress your doctor?',
    'What is a guilty pleasure you share with your gym trainer?',
    'Have you ever stalked the social media of your cousin?',
    'What is a habit you find annoying about a ghost?',
    'Have you ever stolen something from a politician?',
    'Have you ever tried to impress your ex?',
    'Have you ever cried because of your crush?',
    'What would you do if you were stuck in an elevator with your first love?',
    'What is the meanest thing you ever did to your first love?',
    'What is a habit you find annoying about your favorite musician?',
    'Have you ever pretended to like a gift from the last person you texted?',
    'Have you ever forgotten the birthday of your secret admirer?',
    'Have you ever had a crush on your future self?',
    'What would you do if you were stuck in an elevator with your secret admirer?',
    "What is the worst thing you've ever said behind the back of your sibling?",
    "What is the worst thing you've ever said behind the back of your high school principal?",
    'Have you ever given fake advice to your secret admirer?',
    'What is a secret you are keeping from a random Discord user?',
    'What is a guilty pleasure you share with a Twitch streamer?',
    'Have you ever stalked the social media of your past self?',
    'Have you ever pretended to like a gift from your gym trainer?',
    'Have you ever pretended to like a gift from your local barista?',
    'What is the meanest thing you ever did to your boss?',
    'Have you ever ignored a call from your online friend?',
    'Have you ever cried because of your teacher?',
    'Have you ever tried to impress your neighbor?',
    'Have you ever had a crush on the person sitting next to you?',
    'Have you ever been jealous of your favorite musician?',
    'What is your honest opinion of your worst enemy?',
    'Have you ever pretended to like a gift from your best friend?',
    "What is the strangest dream you've had involving your future self?",
    'Have you ever stalked the social media of the person sitting next to you?',
    'What is the weirdest thing you ever asked a politician?',
    'Have you ever judged your pet?',
    'Have you ever had a crush on your grandfather?',
    'What is the meanest thing you ever did to your grandfather?',
    'Have you ever lied to get out of hanging out with your grandfather?',
    'If you had to trade lives with your online friend?',
    "What is the weirdest thought you've had about a delivery driver?",
    'What is a habit you find annoying about your gym trainer?',
    'Have you ever judged the smartest person you know?',
    'Have you ever given fake advice to a Twitch streamer?',
    'What would you do if you were stuck in an elevator with a celebrity?',
    "What is the worst thing you've ever said behind the back of the smartest person you know?",
    'What is the meanest thing you ever did to your gym trainer?',
    "What is the strangest dream you've had involving the person sitting next to you?",
    'Have you ever forgotten the birthday of a YouTuber?',
    'What is your honest opinion of your childhood hero?',
    'Have you ever forgotten the birthday of a random Discord user?',
    'If you had to trade lives with a random Discord user?',
    'Have you ever been jealous of your neighbor?',
    'What would you do if you were stuck in an elevator with your grandfather?',
    'If you had to trade lives with a stranger?',
    'What is your honest opinion of someone you follow on Instagram?',
    'Have you ever lied to get out of hanging out with your favorite actor?',
    'If you had to trade lives with the last person you texted?',
    'Have you ever had a crush on your online friend?',
    "What is the weirdest thought you've had about your neighbor?",
    'What is a secret you are keeping from your favorite musician?',
    'Have you ever pretended to like a gift from your boss?',
    'What is the meanest thing you ever did to your neighbor?',
    'Have you ever snooped through the phone of your boss?',
    'Have you ever judged your childhood hero?',
    'Have you ever stalked the social media of a politician?',
    'Have you ever snooped through the phone of a delivery driver?',
    "What is the most awkward interaction you've had with a Twitch streamer?",
    'Have you ever been jealous of a YouTuber?',
    'Have you ever accidentally sent a text meant for someone else to your secret admirer?',
    'Have you ever snooped through the phone of a celebrity?',
    'What is the funniest memory you have of your ex?',
    'What is a habit you find annoying about your reflection?',
    'Have you ever snooped through the phone of a fictional character?',
    'What would you do if you were stuck in an elevator with your pet?',
    'Have you ever been jealous of a delivery driver?',
    'Have you ever lied to get out of hanging out with the funniest person you know?',
    "What is the most awkward interaction you've had with the smartest person you know?",
    'Have you ever stalked the social media of your secret admirer?',
    "What is the worst thing you've ever said behind the back of the funniest person you know?",
    'Have you ever cried because of a random Discord user?',
    'What is a habit you find annoying about a Twitch streamer?',
    'Have you ever stolen something from your ex?',
    "What is the most awkward interaction you've had with the server owner?",
    "What is the strangest dream you've had involving your grandfather?",
    'What is your honest opinion of your crush?',
    "What is the most awkward interaction you've had with a random Discord user?",
    'Have you ever lied to get out of hanging out with the last person you texted?',
    'Have you ever had a crush on your secret admirer?',
    'Have you ever given fake advice to your sibling?',
    'Have you ever ignored a call from your favorite musician?',
    'Have you ever judged your secret admirer?',
    'Have you ever accidentally sent a text meant for someone else to the last person you texted?',
    'Have you ever stalked the social media of a Twitch streamer?',
    "What is the worst thing you've ever said behind the back of your teacher?",
    "What is the weirdest thought you've had about your cousin?",
    'Have you ever stalked the social media of a ghost?',
    'Have you ever judged your favorite actor?',
    'Have you ever stolen something from the smartest person you know?',
    'What is a habit you find annoying about the server owner?',
    'What is the funniest memory you have of a YouTuber?',
    'Have you ever lied to get out of hanging out with your teacher?',
    'Have you ever given fake advice to your grandfather?',
    "What is the weirdest thought you've had about a stranger?",
    'What is a habit you find annoying about a politician?',
    'What is the weirdest thing you ever asked your local barista?',
    'Have you ever had a crush on your past self?',
    'Have you ever lied to get out of hanging out with a fictional character?',
    'Have you ever pretended to like a gift from a random person on the street?',
    "What is the weirdest thought you've had about your future self?",
    'Have you ever snooped through the phone of your favorite musician?',
    'What is a habit you find annoying about a YouTuber?',
    'Have you ever stolen something from your local barista?',
    'What is the weirdest thing you ever asked your online friend?',
    'What is the meanest thing you ever did to a random Discord user?',
    'What is the weirdest thing you ever asked your future self?',
    'If you had to trade lives with a random person on the street?',
    'What is the weirdest thing you ever asked the last person you texted?',
    'Have you ever had a crush on the smartest person you know?',
    'Have you ever stolen something from a stranger?',
    'Have you ever judged a ghost?',
    'Have you ever ignored a call from your worst enemy?',
    "What is the strangest dream you've had involving a YouTuber?",
    'What is the weirdest thing you ever asked a fictional character?',
    'Have you ever accidentally sent a text meant for someone else to your first love?',
    'Have you ever stalked the social media of a random Discord user?',
    'What would you do if you were stuck in an elevator with your worst enemy?',
    'What is a rumor you heard about your crush?',
    'Have you ever given fake advice to someone you follow on Instagram?',
    'Have you ever given fake advice to the smartest person you know?',
    'What is a rumor you heard about a YouTuber?',
    'Have you ever cried because of your childhood hero?',
    'What is the biggest lie you ever told a random person on the street?',
    'Have you ever accidentally sent a text meant for someone else to the funniest person you know?',
    'Have you ever cried because of your sibling?',
    'Have you ever pretended to like a gift from your pet?',
    'Have you ever lied to get out of hanging out with a ghost?',
    'Have you ever had a crush on someone you follow on Instagram?',
    'Have you ever tried to impress your secret admirer?',
    'What is the weirdest thing you ever asked your best friend?',
    'What would you do if you were stuck in an elevator with the last person you texted?',
    'Have you ever judged your past self?',
    "What is the most embarrassing thing you've ever done in front of a delivery driver?",
    'Have you ever given fake advice to your online friend?',
    'Have you ever forgotten the birthday of the last person you texted?',
    'Have you ever had a crush on your boss?',
    'What is a rumor you heard about your grandfather?',
    'What is the funniest memory you have of your favorite musician?',
    'What is a rumor you heard about your reflection?',
    'Have you ever cried because of a celebrity?',
    'Have you ever given fake advice to your boss?',
    'What is a habit you find annoying about your crush?',
    'Have you ever given fake advice to your teacher?',
    'What is the funniest memory you have of your doctor?',
    'What is the biggest lie you ever told your past self?',
    "What is the strangest dream you've had involving your high school principal?",
    'Have you ever had a crush on your best friend?',
    'Have you ever been jealous of the funniest person you know?',
    "What is the most awkward interaction you've had with a delivery driver?",
    'Have you ever ignored a call from your gym trainer?',
    'Have you ever stolen something from someone you follow on Instagram?',
    'Have you ever tried to impress your pet?',
    'What is the meanest thing you ever did to a fictional character?',
    'What would you do if you were stuck in an elevator with a YouTuber?',
    'What is your honest opinion of the server owner?',
    "What is the most embarrassing thing you've ever done in front of a YouTuber?",
    "What is the most awkward interaction you've had with the funniest person you know?",
    'What is a secret you are keeping from your local barista?',
    'Have you ever forgotten the birthday of a ghost?',
    "What is the most awkward interaction you've had with your high school principal?",
    'Have you ever cried because of a YouTuber?',
    'What is your honest opinion of a random Discord user?',
    'Have you ever lied to get out of hanging out with your past self?',
    'Have you ever pretended to like a gift from your secret admirer?',
    'Have you ever been jealous of your ex?',
    'Have you ever given fake advice to your neighbor?',
    'Have you ever had a crush on the last person you texted?',
    'Have you ever had a crush on your sibling?',
    'What is the biggest lie you ever told someone you follow on Instagram?',
    'Have you ever stalked the social media of your reflection?',
    'What is a rumor you heard about your gym trainer?',
    'Have you ever lied to get out of hanging out with your best friend?',
    'Have you ever pretended to like a gift from your favorite musician?',
    'Have you ever ignored a call from the server owner?',
    'What is the meanest thing you ever did to your ex?',
    'What is a secret you are keeping from your teacher?',
    "What is the most awkward interaction you've had with your first love?",
    'Have you ever accidentally sent a text meant for someone else to your childhood hero?',
    'Have you ever accidentally sent a text meant for someone else to your boss?',
    'Have you ever judged your gym trainer?',
    'Have you ever ignored a call from your secret admirer?',
    'What is a secret you are keeping from your worst enemy?',
    'What is a guilty pleasure you share with your past self?',
    'What is a rumor you heard about the last person you texted?',
    'What is a guilty pleasure you share with your best friend?',
    'What is your honest opinion of the smartest person you know?',
    'What is a habit you find annoying about your local barista?',
    'What is the funniest memory you have of the smartest person you know?',
    'What is a secret you are keeping from your online friend?',
    'Have you ever stalked the social media of your crush?',
    'Have you ever stalked the social media of a YouTuber?',
    "What is the most embarrassing thing you've ever done in front of the smartest person you know?",
    'If you had to trade lives with your first love?',
    'What is the funniest memory you have of your online friend?',
    'If you had to trade lives with your favorite musician?',
    'If you had to trade lives with your high school principal?',
    'What is the weirdest thing you ever asked a stranger?',
    'What is the biggest lie you ever told your sibling?',
    'What is the biggest lie you ever told your crush?',
    'Have you ever had a crush on your reflection?',
    'Have you ever lied to get out of hanging out with someone you follow on Instagram?',
    'What is a secret you are keeping from a YouTuber?',
    'Have you ever ignored a call from your doctor?',
    'What would you do if you were stuck in an elevator with someone you follow on Instagram?',
    'Have you ever accidentally sent a text meant for someone else to a Twitch streamer?',
    'What is the biggest lie you ever told your reflection?',
    'What is a rumor you heard about a Twitch streamer?',
    'Have you ever ignored a call from the last person you texted?',
    'What would you do if you were stuck in an elevator with your best friend?',
    'Have you ever accidentally sent a text meant for someone else to your favorite musician?',
    'Have you ever tried to impress your favorite actor?',
    'What is a rumor you heard about your online friend?',
    'If you had to trade lives with a politician?',
    'What is a guilty pleasure you share with a fictional character?',
    'Have you ever given fake advice to your ex?',
    'What is a rumor you heard about your first love?',
    'What is a guilty pleasure you share with your online friend?',
    'Have you ever snooped through the phone of the smartest person you know?',
    'Have you ever had a crush on your neighbor?',
    'What is the biggest lie you ever told your best friend?',
    'What is your honest opinion of a Twitch streamer?',
    "What is the most awkward interaction you've had with your reflection?",
    'Have you ever stalked the social media of your high school principal?',
    "What is the strangest dream you've had involving your crush?",
    'Have you ever ignored a call from your grandfather?',
    "What is the weirdest thought you've had about your secret admirer?",
    'What would you do if you were stuck in an elevator with your past self?',
    "What is the most embarrassing thing you've ever done in front of your online friend?",
    'What is a rumor you heard about your favorite musician?',
    'Have you ever judged your future self?',
    'Have you ever cried because of a politician?',
    "What is the weirdest thought you've had about your crush?",
    'What is a secret you are keeping from your pet?',
    'Have you ever judged a random Discord user?',
    'Have you ever been jealous of a celebrity?',
    'What is a guilty pleasure you share with someone you follow on Instagram?',
    'What is a rumor you heard about your boss?',
    'Have you ever stalked the social media of the last person you texted?',
    'Have you ever had a crush on a ghost?',
    'Have you ever lied to get out of hanging out with your local barista?',
    'What is the weirdest thing you ever asked a random Discord user?',
    "What is the worst thing you've ever said behind the back of your childhood hero?",
    'Have you ever given fake advice to your pet?',
    "What is the most awkward interaction you've had with a YouTuber?",
    'Have you ever ignored a call from a random Discord user?',
    'What is the weirdest thing you ever asked your high school principal?',
    'What is the funniest memory you have of your pet?',
    "What is the weirdest thought you've had about a ghost?",
    'Have you ever stolen something from your worst enemy?',
    'Have you ever ignored a call from the person sitting next to you?',
    "What is the strangest dream you've had involving a random person on the street?",
    'If you had to trade lives with the funniest person you know?',
    'What is a secret you are keeping from your boss?',
    "What is the most embarrassing thing you've ever done in front of a stranger?",
    'Have you ever given fake advice to your crush?',
    'Have you ever forgotten the birthday of your cousin?',
    'Have you ever pretended to like a gift from someone you follow on Instagram?',
    'Have you ever judged your doctor?',
    'What is the funniest memory you have of the person sitting next to you?',
    'Have you ever given fake advice to your best friend?',
    'What is the weirdest thing you ever asked a random person on the street?',
    'What is a secret you are keeping from the last person you texted?',
    'Have you ever lied to get out of hanging out with your doctor?',
    'Have you ever pretended to like a gift from a random Discord user?',
    "What is the strangest dream you've had involving your local barista?",
    'What is a secret you are keeping from your crush?',
    "What is the most embarrassing thing you've ever done in front of your past self?",
    'Have you ever accidentally sent a text meant for someone else to a random Discord user?',
    'Have you ever ignored a call from a random person on the street?',
    "What is the weirdest thought you've had about your boss?",
    'What is a guilty pleasure you share with your ex?',
    'Have you ever had a crush on a fictional character?',
    'What is the biggest lie you ever told your pet?',
    'If you had to trade lives with your gym trainer?',
    "What is the most embarrassing thing you've ever done in front of your best friend?",
    'If you had to trade lives with your favorite actor?',
    "What is the most embarrassing thing you've ever done in front of your boss?",
    'Have you ever snooped through the phone of your gym trainer?',
    'What would you do if you were stuck in an elevator with your cousin?',
    'What would you do if you were stuck in an elevator with the funniest person you know?',
    'What is a rumor you heard about your childhood hero?',
    'Have you ever lied to get out of hanging out with a celebrity?',
    'Have you ever snooped through the phone of a random Discord user?',
    'What is your honest opinion of your cousin?',
    'Have you ever cried because of your past self?',
    "What is the strangest dream you've had involving your reflection?",
    'Have you ever cried because of your reflection?',
    'Have you ever cried because of your secret admirer?',
    'Have you ever judged your boss?',
    'What is a habit you find annoying about your pet?',
    'Have you ever judged a politician?',
    'Have you ever tried to impress your gym trainer?',
    'Have you ever forgotten the birthday of your reflection?',
    'What would you do if you were stuck in an elevator with a random person on the street?',
    "What is the worst thing you've ever said behind the back of a stranger?",
    "What is the strangest dream you've had involving your first love?",
    'What is the biggest lie you ever told a Twitch streamer?',
    "What is the worst thing you've ever said behind the back of a YouTuber?",
    'Have you ever lied to get out of hanging out with a YouTuber?',
    'Have you ever cried because of a stranger?',
    'Have you ever accidentally sent a text meant for someone else to a ghost?',
    'What is the meanest thing you ever did to the funniest person you know?',
    'Have you ever stolen something from the funniest person you know?',
    "What is the strangest dream you've had involving the server owner?",
    'Have you ever been jealous of your favorite actor?',
    "What is the most embarrassing thing you've ever done in front of your secret admirer?",
    'Have you ever stolen something from your grandfather?',
    'Have you ever judged your best friend?',
    'What is the biggest lie you ever told your boss?',
    'What is the biggest lie you ever told your grandfather?',
    "What is the worst thing you've ever said behind the back of a politician?",
    "What is the worst thing you've ever said behind the back of your first love?",
    'What is a rumor you heard about a fictional character?',
    'Have you ever stolen something from a random person on the street?',
    'Have you ever forgotten the birthday of your childhood hero?',
    'Have you ever tried to impress your favorite musician?',
    'What is the biggest lie you ever told your future self?',
    'What is your honest opinion of your favorite actor?',
    'Have you ever snooped through the phone of your childhood hero?',
    'Have you ever stalked the social media of your teacher?',
    'Have you ever accidentally sent a text meant for someone else to your worst enemy?',
    "What is the weirdest thought you've had about your gym trainer?",
    'What is the meanest thing you ever did to someone you follow on Instagram?',
    "What is the worst thing you've ever said behind the back of your cousin?",
    'Have you ever forgotten the birthday of a delivery driver?',
    'Have you ever forgotten the birthday of your first love?',
    'Have you ever pretended to like a gift from your teacher?',
    'What is the biggest lie you ever told your neighbor?',
    'Have you ever snooped through the phone of a random person on the street?',
    'Have you ever lied to get out of hanging out with a Twitch streamer?',
    'What is the funniest memory you have of your best friend?',
    'Have you ever pretended to like a gift from a stranger?',
    'Have you ever been jealous of your first love?',
    'Have you ever stolen something from your childhood hero?',
    'Have you ever snooped through the phone of the server owner?',
    'What is the weirdest thing you ever asked your secret admirer?',
    'What would you do if you were stuck in an elevator with your ex?',
    'What is a guilty pleasure you share with the last person you texted?',
    'What would you do if you were stuck in an elevator with your gym trainer?',
    'If you had to trade lives with your future self?',
    "What is the most embarrassing thing you've ever done in front of your grandfather?",
    "What is the weirdest thought you've had about the person sitting next to you?",
    'Have you ever pretended to like a gift from your crush?',
    'Have you ever cried because of your best friend?',
    'Have you ever snooped through the phone of your crush?',
    'Have you ever lied to get out of hanging out with your favorite musician?',
    'What is the funniest memory you have of someone you follow on Instagram?',
    'Have you ever snooped through the phone of your secret admirer?',
    'What is a secret you are keeping from a politician?',
    'Have you ever snooped through the phone of the person sitting next to you?',
    'What is a secret you are keeping from your gym trainer?',
    'What is a habit you find annoying about a random Discord user?',
    'Have you ever pretended to like a gift from your neighbor?',
    "What is the worst thing you've ever said behind the back of your past self?",
    'Have you ever been jealous of a random person on the street?',
    'Have you ever snooped through the phone of your high school principal?',
    'What is the biggest lie you ever told your worst enemy?',
    "What is the most embarrassing thing you've ever done in front of your gym trainer?",
    'Have you ever cried because of your grandfather?',
    "What is the worst thing you've ever said behind the back of your ex?",
    'If you had to trade lives with a ghost?',
    "What is the weirdest thought you've had about your favorite musician?",
    "What is the strangest dream you've had involving the last person you texted?",
    "What is the strangest dream you've had involving your online friend?",
    'What is the meanest thing you ever did to your worst enemy?',
    "What is the strangest dream you've had involving a random Discord user?",
    'Have you ever forgotten the birthday of your sibling?',
    'What is the biggest lie you ever told your secret admirer?',
    'Have you ever ignored a call from your neighbor?',
    'What is the biggest lie you ever told your favorite actor?',
    'What is a secret you are keeping from your favorite actor?',
    "What is the worst thing you've ever said behind the back of your best friend?",
    'If you had to trade lives with someone you follow on Instagram?',
    'What is the weirdest thing you ever asked the server owner?',
    "What is the weirdest thought you've had about your childhood hero?",
    'Have you ever judged your local barista?',
    'What is a guilty pleasure you share with the server owner?',
    'Have you ever stolen something from a fictional character?',
    'Have you ever lied to get out of hanging out with your cousin?',
    'What is a rumor you heard about the smartest person you know?',
    'Have you ever accidentally sent a text meant for someone else to your neighbor?',
    'Have you ever given fake advice to your favorite actor?',
    "What is the most embarrassing thing you've ever done in front of the funniest person you know?",
    'Have you ever accidentally sent a text meant for someone else to your ex?',
    "What is the strangest dream you've had involving your favorite actor?",
    'Have you ever tried to impress a celebrity?',
    'What is the meanest thing you ever did to your teacher?',
    'If you had to trade lives with your sibling?',
    "What is the strangest dream you've had involving your pet?",
    'Have you ever been jealous of your childhood hero?',
    "What is the most embarrassing thing you've ever done in front of your neighbor?",
    'Have you ever pretended to like a gift from a delivery driver?',
    'Have you ever lied to get out of hanging out with a delivery driver?',
    'Have you ever ignored a call from a stranger?',
    'What is the biggest lie you ever told a politician?',
    "What is the most embarrassing thing you've ever done in front of a politician?",
    "What is the most awkward interaction you've had with your sibling?",
    'Have you ever tried to impress your crush?',
    "What is the most awkward interaction you've had with your cousin?",
    'Have you ever accidentally sent a text meant for someone else to someone you follow on Instagram?',
    'If you had to trade lives with your pet?',
    'Have you ever forgotten the birthday of your gym trainer?',
    'What is the funniest memory you have of a stranger?',
    'What is the funniest memory you have of a random Discord user?',
    'What is your honest opinion of your first love?',
    "What is the worst thing you've ever said behind the back of your pet?",
    'Have you ever ignored a call from your best friend?',
    'Have you ever given fake advice to the person sitting next to you?',
    'What is a rumor you heard about your secret admirer?',
    'Have you ever stalked the social media of a celebrity?',
    'Have you ever stalked the social media of your worst enemy?',
    'What is the weirdest thing you ever asked your favorite actor?',
    'What is the weirdest thing you ever asked your first love?',
    "What is the most awkward interaction you've had with your local barista?",
    'What is a guilty pleasure you share with your secret admirer?',
    'Have you ever ignored a call from your local barista?',
    'What is the funniest memory you have of a ghost?',
    'What is the funniest memory you have of your secret admirer?',
    'What would you do if you were stuck in an elevator with the person sitting next to you?',
    'What is a secret you are keeping from a delivery driver?',
    'What is your honest opinion of the funniest person you know?',
    'Have you ever pretended to like a gift from your cousin?',
    'Have you ever tried to impress the funniest person you know?',
    'What is a rumor you heard about your sibling?',
    'What is your honest opinion of a delivery driver?',
    'What is the funniest memory you have of your sibling?',
    'Have you ever lied to get out of hanging out with the smartest person you know?',
    'What is the meanest thing you ever did to a YouTuber?',
    'Have you ever snooped through the phone of your grandfather?',
    'Have you ever forgotten the birthday of your favorite actor?',
    'What is the weirdest thing you ever asked a delivery driver?',
    'Have you ever had a crush on your ex?',
    'What is the meanest thing you ever did to your pet?',
    'What is the funniest memory you have of your neighbor?',
    'Have you ever tried to impress your grandfather?',
    'Have you ever judged your sibling?',
    'What is a habit you find annoying about your high school principal?',
    'What is a habit you find annoying about your sibling?',
    'What is a habit you find annoying about your grandfather?',
    'Have you ever tried to impress your online friend?',
    'Have you ever had a crush on your worst enemy?',
    "What is the most embarrassing thing you've ever done in front of your local barista?",
    'Have you ever snooped through the phone of your sibling?',
    'What is the weirdest thing you ever asked your reflection?',
    'What is a secret you are keeping from your cousin?',
    'Have you ever cried because of someone you follow on Instagram?',
    'Have you ever had a crush on a random Discord user?',
    'Have you ever given fake advice to the last person you texted?',
    'If you had to trade lives with your doctor?',
    "What is the weirdest thought you've had about a celebrity?",
    'Have you ever lied to get out of hanging out with your childhood hero?',
    'What is a habit you find annoying about the person sitting next to you?',
    'If you had to trade lives with a fictional character?',
    'Have you ever forgotten the birthday of the funniest person you know?',
    'Have you ever lied to get out of hanging out with your first love?',
    'Have you ever tried to impress your high school principal?',
    "What is the weirdest thought you've had about the funniest person you know?",
    'What is a habit you find annoying about your best friend?',
    "What is the most embarrassing thing you've ever done in front of your reflection?",
    'Have you ever lied to get out of hanging out with your worst enemy?',
    'Have you ever judged your online friend?',
    'What is a rumor you heard about your favorite actor?',
    'What is the biggest lie you ever told your favorite musician?',
    "What is the most embarrassing thing you've ever done in front of a fictional character?",
    'What is a habit you find annoying about your neighbor?',
    'Have you ever snooped through the phone of your first love?',
    'What is the weirdest thing you ever asked your grandfather?',
    'What would you do if you were stuck in an elevator with a ghost?',
    'Have you ever judged a YouTuber?',
    'What is the biggest lie you ever told a stranger?',
    'What is your honest opinion of your sibling?',
    "What is the worst thing you've ever said behind the back of the person sitting next to you?",
    "What is the worst thing you've ever said behind the back of a random person on the street?",
    'Have you ever snooped through the phone of a YouTuber?',
    'What is the meanest thing you ever did to a Twitch streamer?',
    'Have you ever accidentally sent a text meant for someone else to your grandfather?',
    'Have you ever pretended to like a gift from your grandfather?',
    'What is the biggest lie you ever told your doctor?',
    'Have you ever had a crush on your favorite actor?',
    "What is the most embarrassing thing you've ever done in front of your cousin?",
    'Have you ever forgotten the birthday of a random person on the street?',
    'What is a habit you find annoying about your online friend?',
    'Have you ever stolen something from your gym trainer?',
    "What is the strangest dream you've had involving your sibling?",
    'Have you ever pretended to like a gift from your future self?',
    'Have you ever tried to impress your childhood hero?',
    "What is the weirdest thought you've had about a politician?",
    'What would you do if you were stuck in an elevator with your doctor?',
    "What is the most embarrassing thing you've ever done in front of your pet?",
    'Have you ever cried because of a Twitch streamer?',
    "What is the most awkward interaction you've had with your future self?",
    'Have you ever given fake advice to your local barista?',
    "What is the most awkward interaction you've had with the person sitting next to you?",
    "What is the most awkward interaction you've had with your pet?",
    "What is the most awkward interaction you've had with a fictional character?",
    'What would you do if you were stuck in an elevator with a random Discord user?',
    'What is the meanest thing you ever did to your crush?',
    'What is a secret you are keeping from your doctor?',
    'Have you ever accidentally sent a text meant for someone else to your local barista?',
    'What is a rumor you heard about your local barista?',
    'Have you ever ignored a call from a Twitch streamer?',
    'Have you ever judged a stranger?',
    "What is the worst thing you've ever said behind the back of your secret admirer?",
    'Have you ever been jealous of a Twitch streamer?',
    'Have you ever given fake advice to your past self?',
    "What is the weirdest thought you've had about your teacher?",
    'What is a guilty pleasure you share with your cousin?',
    "What is the most awkward interaction you've had with your favorite musician?",
    'Have you ever ignored a call from a celebrity?',
    'What is your honest opinion of your favorite musician?',
    'Have you ever pretended to like a gift from the smartest person you know?',
    'Have you ever pretended to like a gift from the server owner?',
    'Have you ever given fake advice to your favorite musician?',
    'What is the biggest lie you ever told the funniest person you know?',
    "What is the weirdest thought you've had about your past self?",
    'Have you ever tried to impress your boss?',
    "What is the most awkward interaction you've had with the last person you texted?",
    'Have you ever had a crush on your pet?',
    'What is the funniest memory you have of your first love?',
    'What is the biggest lie you ever told a fictional character?',
    'Have you ever stolen something from your boss?',
    'What is the meanest thing you ever did to the smartest person you know?',
    'Have you ever given fake advice to a delivery driver?',
    'What is your honest opinion of the person sitting next to you?',
    'If you had to trade lives with a YouTuber?',
    'Have you ever given fake advice to a random person on the street?',
    'Have you ever snooped through the phone of your past self?',
    'What is a rumor you heard about your ex?',
    "What is the most embarrassing thing you've ever done in front of a random Discord user?",
    'What is the weirdest thing you ever asked your pet?',
    "What is the most awkward interaction you've had with your secret admirer?",
    'What is the meanest thing you ever did to your best friend?',
    "What is the most awkward interaction you've had with a celebrity?",
    "What is the weirdest thought you've had about a YouTuber?",
    'Have you ever tried to impress the server owner?',
    'What is a rumor you heard about someone you follow on Instagram?',
    "What is the most embarrassing thing you've ever done in front of the last person you texted?",
    'Have you ever been jealous of your past self?',
    "What is the weirdest thought you've had about your high school principal?",
    'Have you ever pretended to like a gift from your worst enemy?',
    'Have you ever ignored a call from someone you follow on Instagram?',
    'Have you ever forgotten the birthday of your future self?',
    'Have you ever tried to impress your worst enemy?',
    'Have you ever tried to impress your best friend?',
    'Have you ever cried because of the server owner?',
    'What is a guilty pleasure you share with your sibling?',
    'Have you ever pretended to like a gift from a Twitch streamer?',
    'Have you ever stolen something from a delivery driver?',
    'What is the weirdest thing you ever asked your favorite musician?',
    'What is your honest opinion of your future self?',
    'Have you ever stalked the social media of your childhood hero?',
    'Have you ever cried because of a ghost?',
    "What is the most awkward interaction you've had with your worst enemy?",
    'Have you ever lied to get out of hanging out with your secret admirer?',
    'Have you ever ignored a call from your teacher?',
    'What is a habit you find annoying about your teacher?',
    'Have you ever forgotten the birthday of the server owner?',
    "What is the weirdest thought you've had about your sibling?",
    'What is a habit you find annoying about your boss?',
    "What is the most embarrassing thing you've ever done in front of your first love?",
    'What would you do if you were stuck in an elevator with a stranger?',
    'Have you ever tried to impress your teacher?',
    'What is a guilty pleasure you share with your teacher?',
    'What is the meanest thing you ever did to your favorite actor?',
    'Have you ever had a crush on your teacher?',
    'Have you ever snooped through the phone of your neighbor?',
    "What is the strangest dream you've had involving someone you follow on Instagram?",
    'What would you do if you were stuck in an elevator with your local barista?',
    'If you had to trade lives with your worst enemy?',
    'Have you ever been jealous of a fictional character?',
    'Have you ever pretended to like a gift from your past self?',
    'Have you ever cried because of your first love?',
    "What is the most embarrassing thing you've ever done in front of a celebrity?",
    'Have you ever tried to impress your first love?',
    'What is a secret you are keeping from your first love?',
    'Have you ever stolen something from a YouTuber?',
    'Have you ever tried to impress a random Discord user?',
    'Have you ever been jealous of the server owner?',
    'Have you ever judged someone you follow on Instagram?',
    'Have you ever tried to impress your cousin?',
    'What is your honest opinion of your past self?',
    'Have you ever forgotten the birthday of your online friend?',
    'Have you ever ignored a call from your past self?',
    'What would you do if you were stuck in an elevator with the server owner?',
    'What is a secret you are keeping from the smartest person you know?',
    'What would you do if you were stuck in an elevator with your future self?',
    'Have you ever snooped through the phone of your reflection?',
    'What is your honest opinion of a random person on the street?',
    'Have you ever accidentally sent a text meant for someone else to the server owner?',
    'Have you ever given fake advice to your future self?',
    'Have you ever judged your reflection?',
    "What is the worst thing you've ever said behind the back of your boss?",
    'Have you ever been jealous of your crush?',
    'Have you ever forgotten the birthday of your local barista?',
    'Have you ever judged your cousin?',
    'What is a secret you are keeping from a random person on the street?',
    'Have you ever cried because of the person sitting next to you?',
    "What is the strangest dream you've had involving your gym trainer?",
    'What is the biggest lie you ever told a YouTuber?',
    'What is a guilty pleasure you share with the funniest person you know?',
    "What is the worst thing you've ever said behind the back of your local barista?",
    'Have you ever pretended to like a gift from your ex?',
    'Have you ever forgotten the birthday of your ex?',
    "What is the strangest dream you've had involving a ghost?",
    'Have you ever been jealous of your reflection?',
    "What is the worst thing you've ever said behind the back of your worst enemy?",
    'What is your honest opinion of a ghost?',
    'Have you ever accidentally sent a text meant for someone else to your crush?',
    'Have you ever had a crush on a Twitch streamer?',
    "What is the strangest dream you've had involving the funniest person you know?",
    'What is the meanest thing you ever did to the last person you texted?',
    'Have you ever snooped through the phone of a stranger?',
    'Have you ever stalked the social media of your ex?',
    'What is a habit you find annoying about your cousin?',
    'Have you ever ignored a call from your favorite actor?',
    'What would you do if you were stuck in an elevator with a Twitch streamer?',
    "What is the most awkward interaction you've had with your gym trainer?",
    'What is your honest opinion of your grandfather?',
    'Have you ever pretended to like a gift from your high school principal?',
    'Have you ever snooped through the phone of your teacher?',
    'Have you ever been jealous of your cousin?',
    'What is your honest opinion of your online friend?',
    'Have you ever been jealous of the person sitting next to you?',
    "What is the worst thing you've ever said behind the back of your grandfather?",
    "What is the most awkward interaction you've had with your online friend?",
    'If you had to trade lives with the server owner?',
    'Have you ever forgotten the birthday of the smartest person you know?',
    "What is the most embarrassing thing you've ever done in front of the server owner?",
    'Have you ever lied to get out of hanging out with your boss?',
    'Have you ever judged a delivery driver?',
    'Have you ever pretended to like a gift from your favorite actor?',
    "What is the weirdest thought you've had about the smartest person you know?",
    'What is the biggest lie you ever told a random Discord user?',
    'Have you ever given fake advice to your reflection?',
    "What is the worst thing you've ever said behind the back of your reflection?",
    'Have you ever given fake advice to your childhood hero?',
    'What is a secret you are keeping from your future self?',
    'Have you ever given fake advice to your first love?',
    'Have you ever ignored a call from your high school principal?',
    "What is the most embarrassing thing you've ever done in front of a ghost?",
    "What is the worst thing you've ever said behind the back of a Twitch streamer?",
    'What is the meanest thing you ever did to your reflection?',
    "What is the strangest dream you've had involving your favorite musician?",
    'Have you ever pretended to like a gift from your reflection?',
    'Have you ever stolen something from a random Discord user?',
    'What is the weirdest thing you ever asked your teacher?',
    'Have you ever accidentally sent a text meant for someone else to your past self?',
    'Have you ever accidentally sent a text meant for someone else to the person sitting next to you?',
    'What is a guilty pleasure you share with the smartest person you know?',
    'What is your honest opinion of your secret admirer?',
    'Have you ever snooped through the phone of a politician?',
    "What is the strangest dream you've had involving your neighbor?",
    "What is the most awkward interaction you've had with your crush?",
    'What is your honest opinion of your ex?',
    'Have you ever lied to get out of hanging out with a random person on the street?',
    'Have you ever judged your first love?',
    'Have you ever pretended to like a gift from your doctor?',
    'Have you ever forgotten the birthday of your worst enemy?',
    'Have you ever judged your grandfather?',
    'Have you ever lied to get out of hanging out with a random Discord user?',
    'Have you ever been jealous of your high school principal?',
    'Have you ever snooped through the phone of your online friend?',
    'What is the meanest thing you ever did to the server owner?',
    'Have you ever forgotten the birthday of a celebrity?',
    'Have you ever had a crush on your local barista?',
    'What is the meanest thing you ever did to a random person on the street?',
    'What is a guilty pleasure you share with your first love?',
    'What is the meanest thing you ever did to a celebrity?',
    'What is the biggest lie you ever told your high school principal?',
    'Have you ever given fake advice to a stranger?',
    'Have you ever stolen something from a Twitch streamer?',
    'Have you ever stalked the social media of the server owner?',
    'Have you ever stolen something from your past self?',
    'What is the funniest memory you have of your teacher?',
    'What is your honest opinion of your gym trainer?',
    'What is the meanest thing you ever did to a stranger?',
    'Have you ever given fake advice to a ghost?',
    'What is the weirdest thing you ever asked your childhood hero?',
    'What is your honest opinion of a celebrity?',
    'Have you ever stolen something from your cousin?',
    'What is a guilty pleasure you share with your doctor?',
    'Have you ever pretended to like a gift from a ghost?',
    'Have you ever accidentally sent a text meant for someone else to your teacher?',
    'Have you ever tried to impress a ghost?',
    'What is the meanest thing you ever did to your cousin?',
    "What is the most awkward interaction you've had with a stranger?",
    "What is the weirdest thought you've had about your favorite actor?",
    'Have you ever stolen something from your favorite actor?',
    "What is the strangest dream you've had involving your ex?",
    'What is a guilty pleasure you share with a politician?',
    'Have you ever tried to impress the person sitting next to you?',
    'Have you ever cried because of the smartest person you know?',
    "What is the most awkward interaction you've had with your past self?",
    'Have you ever been jealous of your secret admirer?',
    'What is the funniest memory you have of your reflection?',
    'Have you ever judged your favorite musician?',
    'Have you ever stalked the social media of your favorite actor?',
    'What is the funniest memory you have of a politician?',
    'Have you ever stalked the social media of a delivery driver?',
    "What is the weirdest thought you've had about your first love?",
    'Have you ever given fake advice to your doctor?',
    'Have you ever cried because of your doctor?',
    'What is the weirdest thing you ever asked your past self?',
    'Have you ever pretended to like a gift from the person sitting next to you?',
    'Have you ever accidentally sent a text meant for someone else to your reflection?',
    'What is the funniest memory you have of your boss?',
    "What is the most awkward interaction you've had with your teacher?",
    'What is a habit you find annoying about a delivery driver?',
    'What is a guilty pleasure you share with your grandfather?',
    "What is the worst thing you've ever said behind the back of the last person you texted?",
    "What is the strangest dream you've had involving the smartest person you know?",
    'Have you ever stalked the social media of the funniest person you know?',
    'Have you ever forgotten the birthday of your doctor?',
    'What is your honest opinion of a politician?',
    'What is a rumor you heard about a random Discord user?',
    'Have you ever had a crush on a delivery driver?',
    'Have you ever ignored a call from the funniest person you know?',
    'Have you ever snooped through the phone of the last person you texted?',
    'Have you ever had a crush on your childhood hero?',
    'Have you ever stolen something from your first love?',
    'If you had to trade lives with the smartest person you know?',
    'Have you ever been jealous of your boss?',
    "What is the most embarrassing thing you've ever done in front of your teacher?",
    'Have you ever ignored a call from your future self?',
    "What is the strangest dream you've had involving your past self?",
    'What is a habit you find annoying about a random person on the street?',
    'Have you ever stolen something from a ghost?',
    'Have you ever cried because of your gym trainer?',
    'What would you do if you were stuck in an elevator with your sibling?'
]

MORE_DARES = [
    "Turn on your camera in a Voice Channel, put a shoe on your head, and keep it there for 1 minute.",
    "DM the 3rd person on your online list 'I know what you did.' and screenshot their reply.",
    "Turn your camera on in VC and try not to blink for 30 seconds.",
    "Send a DM to the server owner asking for admin privileges, then immediately say 'Sorry, my cat walked on my keyboard.'",
    "Screen share and draw a picture of a duck in MS Paint/Paint 3D in 1 minute.",
    "Turn on your camera in VC and eat a slice of lemon without making a face (or act like you are if you don't have one).",
    "Change your status to 'I smell like cheese' for the next 12 hours.",
    "Send a voice message in the chat trying to do a Mickey Mouse impression.",
    "Screen share your Spotify/Apple Music and let the chat judge your top 5 recently played songs.",
    "Join VC and for the next 3 minutes, you must start every sentence with 'According to my calculations...'.",
    "Ping a random person in the server and say 'You owe me 5 bucks.'",
    "Turn on your camera and try to balance a book on your head for 1 minute.",
    "Screen share your browser extensions and explain why you need each one.",
    "Join VC, unmute, loudly sigh, then mute yourself again without explaining.",
    "Send a picture of the inside of your fridge to the chat.",
    "Change your nickname to the last thing you ate for the next hour.",
    "Turn on your camera and give a 1-minute dramatic monologue about a potato.",
    "Send a voice message of you reading the rules of the server in a dramatic voice.",
    "Join VC and do your best impression of another server member for 30 seconds.",
    "Screen share and let us see the last 3 photos you saved on your phone/PC.",
    "Turn on your camera, close your eyes, and try to draw a house on a piece of paper.",
    "Change your Discord About Me to 'I secretly love eating plain mayo.' for a day.",
    "Send a voice message trying to rap the fastest verse you know.",
    "Screen share your desktop background and explain why you chose it.",
    "Join VC and talk like a robot for the next 5 minutes.",
    "Turn on your camera and show us your best dance move.",
    "Send a voice message of you trying to speak an alien language.",
    "Screen share and take a random 'Which bread type are you?' Buzzfeed quiz.",
    "Change your profile picture to a default Discord avatar for the next 3 days.",
    "Join VC and describe your dream date but replace every noun with 'chicken'.",
    "Turn on your camera and try to juggle 3 items (even if it's just balled-up socks).",
    "Send a voice message of you crying dramatically over a minor inconvenience (like dropping a pen).",
    "Screen share your Steam/Epic Games library and let us judge your playtime.",
    "Join VC and aggressively compliment someone for 1 minute straight.",
    "Turn on your camera and wear a pair of sunglasses indoors for the rest of your VC stay.",
    "Change your nickname to 'Certified Yapper' and you must type a 50-word essay for your next 3 messages.",
    "Send a voice message singing a nursery rhyme like it's a heavy metal song.",
    "Screen share and show us the oldest email in your inbox.",
    "Join VC and anytime someone speaks, you must say 'Interesting...' before you reply.",
    "Turn on your camera and stare directly into it without smiling for 1 minute.",
    "Send a voice message telling a terribly unfunny joke, and laugh uncontrollably at the end.",
    "Screen share and quickly type 'how to communicate with aliens' in Google, then close it immediately.",
    "Join VC and pretend you are ordering food at a drive-thru.",
    "Turn on your camera and show us the 5 closest objects to you.",
    "Change your Discord status to 'Looking for a sugar daddy/mommy' for the next 24 hours.",
    "Send a voice message whispering a spooky ghost story.",
    "Screen share and try to type the alphabet as fast as you can on a typing test website.",
    "Join VC and act like you are an AI assistant answering prompts for 2 minutes.",
    "Turn on your camera and act out a scene from your favorite movie.",
    "Send a voice message of you beatboxing for 30 seconds.",
    "Screen share and show us your customized Discord settings (theme, profile colors, etc.).",
    "Join VC and only communicate in grunts and nods for the next 5 minutes.",
    "Turn on your camera and show off your favorite piece of clothing.",
    "Change your nickname to 'Local Menace' and ping someone random with just '?'.",
    "Send a voice message trying to sell us a used tissue.",
    "Screen share and play a quick game of Minesweeper or Solitaire.",
    "Join VC and pretend you are doing a YouTube vlog intro and outro.",
    "Turn on your camera and try to lick your elbow (or convincingly fake it).",
    "Send a voice message reading the last text you received out loud.",
    "Screen share and show us the weirdest app you have installed.",
    "Join VC and pretend you are a news anchor reporting on a mundane event in your room.",
    "Turn on your camera and do your best evil villain laugh.",
    "Change your profile picture to a picture of a toe for 24 hours.",
    "Send a voice message singing the alphabet backwards.",
    "Screen share and let the chat choose a random YouTube video for you to watch for 1 minute.",
    "Join VC and speak incredibly slowly for the next 3 minutes.",
    "Turn on your camera and show us a talent you have.",
    "Send a voice message pretending to be a flight attendant making an announcement.",
    "Screen share and show us your most used emojis.",
    "Join VC and pretend you are in a high-speed car chase while talking."
]