MORE_TRUTHS = [
    'What is your biggest fear?', 'Have you ever cheated on a test?', 'What is the most embarrassing thing you have ever done?',
    'What is a secret you have never told anyone?', 'Who was your first crush?', 'Have you ever lied to your parents?',
    'What is the worst trouble you have ever been in?', 'If you could be invisible for a day, what would you do?',
    'What is a habit you have that you think is completely gross?', 'What is the longest you have gone without showering?',
    'Have you ever broken something and blamed someone else?', 'If you had to kiss one person in this server, who would it be?',
    'What is the most embarrassing message you have accidentally sent to the wrong person?', 'Have you ever been caught picking your nose?',
    'What is your weirdest flex?', 'What is the most awkward date you have ever been on?', 'Have you ever stolen anything?',
    'What is the biggest lie you have ever told?', 'Have you ever ghosted someone?', 'What is your most embarrassing nickname?',
    'What is the weirdest dream you have ever had?', 'Who do you secretly stalk on social media?', 'Have you ever pretended to be sick to get out of something?',
    'What is the most childish thing you still do?', 'Have you ever eavesdropped on a conversation?', 'What is the dumbest thing you have done on a dare?',
    'Who is your secret idol?', 'What is the most cringe-worthy thing you have posted online?', 'Have you ever peed in a pool?',
    'What is the most ridiculous rumor you have heard about yourself?', 'Have you ever had a crush on a teacher?',
    'What is your guilty pleasure song?', 'What is the weirdest food combination you enjoy?', 'Have you ever lied about your age?',
    'What is the most embarrassing thing your parents have caught you doing?', 'Have you ever ruined a surprise party?',
    'What is the worst gift you have ever received and pretended to like?', 'Have you ever worn the same underwear two days in a row?',
    'What is the most embarrassing thing you have searched for on Google?', 'Have you ever fallen asleep in public?',
    'What is the worst haircut you have ever had?', 'Have you ever tripped and fallen in front of a crowd?',
    'What is the most embarrassing thing you have done while sleepwalking?', 'Have you ever forgotten someones name immediately after they introduced themselves?',
    'What is the weirdest thing you do when you are alone?', 'Have you ever practiced kissing in the mirror?',
    'What is the most embarrassing thing you have said to a crush?', 'Have you ever laughed so hard you snorted?',
    'What is the worst advice you have ever given someone?', 'Have you ever accidentally liked an old photo while stalking someone on Instagram?',
    'What is the most embarrassing thing you have done in a video game?', 'Have you ever cried during a movie? Which one?',
    'What is the weirdest thing you have bought online?', 'Have you ever been caught talking to yourself?',
    'What is the most embarrassing thing you have worn?', 'Have you ever accidentally spit on someone while talking?',
    'What is the worst joke you have ever told that nobody laughed at?', 'Have you ever tripped over nothing?',
    'What is the most embarrassing thing you have done on a Zoom call?', 'Have you ever sent a text to the person it was about?',
    'What is the weirdest rumor you have believed?', 'Have you ever been caught picking a wedgie?',
    'What is the most embarrassing thing you have done at a party?', 'Have you ever pretended to know a language you dont?',
    'What is the worst excuse you have used to cancel plans?', 'Have you ever accidentally insulted someone to their face?',
    'What is the most embarrassing thing you have done while trying to impress someone?', 'Have you ever waved at someone who wasnt waving at you?',
    'What is the weirdest thing you have eaten?', 'Have you ever been caught singing in the shower?',
    'What is the most embarrassing thing you have done at the gym?', 'Have you ever forgotten where you parked your car?',
    'What is the worst injury you have gotten from doing something stupid?', 'Have you ever been caught taking a selfie?',
    'What is the most embarrassing thing you have done on public transportation?', 'Have you ever accidentally sent a romantic text to a family member?',
    'What is the weirdest thing you are afraid of?', 'Have you ever been caught stalking someone online?',
    'What is the most embarrassing thing you have done while drunk (if applicable)?', 'Have you ever accidentally walked into the wrong restroom?',
    'What is the worst mistake you have made at work/school?', 'Have you ever been caught picking your teeth?',
    'What is the most embarrassing thing you have done while dancing?', 'Have you ever accidentally said "I love you" to someone you shouldnt have?',
    'What is the weirdest thing you have found in your food?', 'Have you ever been caught checking yourself out in a window?',
    'What is the most embarrassing thing you have done in a group chat?', 'Have you ever accidentally sent a screenshot to the person you screenshotted?',
    'What is the worst thing you have cooked?', 'Have you ever been caught smelling your own armpits?',
    'What is the most embarrassing thing you have done while trying to be cool?', 'Have you ever accidentally called your teacher "Mom" or "Dad"?',
    'What is the weirdest thing you have done to get someones attention?', 'Have you ever been caught picking a scab?',
    'What is the most embarrassing thing you have done while singing karaoke?', 'Have you ever accidentally sent a voice note you didnt mean to?',
    'What is the worst thing you have done out of anger?', 'Have you ever been caught looking at inappropriate content?',
    'What is the most embarrassing thing you have done in front of a mirror?', 'Have you ever accidentally liked a post from years ago?'
]

MORE_DARES = [
    'Send a voice message of you singing the chorus of your favorite song.', 'Type a message using only your nose.',
    'Send the most embarrassing photo in your camera roll.', 'Change your Discord nickname to something silly for the next 10 minutes.',
    'Write a 3-line poem about the server owner.', 'Send a message to your crush saying "I love you" (or a friend if you dont have one).',
    'Act like a dog for your next 3 messages.', 'Post a selfie with a funny face.',
    'Confess something embarrassing you did today.', 'Give a random server member a compliment.',
    'Speak in Shakespearean English for the next 5 minutes.', 'Spam 5 random emojis in the chat.',
    'Tell a joke. If no one laughs, you have to do another dare.', 'Send your most recently used emoji 10 times.',
    'Change your profile picture to a meme for the rest of the day.', 'Do 10 pushups and send a video (or just say you did them).',
    'Drink a glass of water without using your hands.', 'Eat a spoonful of hot sauce (or mustard/ketchup).',
    'Call a random friend and sing "Happy Birthday" to them.', 'Do your best impression of a famous celebrity.',
    'Balance a spoon on your nose for 10 seconds.', 'Draw a picture blindfolded and share it.',
    'Text your mom "I just got married!" and share her response.', 'Do a silly dance for 30 seconds.',
    'Eat a raw piece of onion or garlic.', 'Talk with a fake accent for the next 10 minutes.',
    'Let someone in the server choose your next avatar.', 'Send a voice note of you doing an evil laugh.',
    'Write a love letter to your favorite food.', 'Do 20 jumping jacks.',
    'Try to lick your elbow.', 'Post a screenshot of your YouTube watch history.',
    'Send a voice note of you trying to rap.', 'Make a funny face and keep it that way for 2 minutes.',
    'Talk in the third person for the next 15 minutes.', 'Send a message to your best friend saying you are mad at them (and then say its a dare).',
    'Put an ice cube down your shirt and leave it there until it melts.', 'Try to juggle 3 items of your choice.',
    'Send a voice note of you making animal noises.', 'Write a short story using only emojis.',
    'Let another player ask you a question that you must answer truthfully.', 'Do a plank for 1 minute.',
    'Send a picture of the inside of your fridge.', 'Try to touch your nose with your tongue.',
    'Send a voice note of you whispering a secret.', 'Post a screenshot of your recent emojis.',
    'Do your best impression of another server member.', 'Send a message to a random person saying "I know what you did."',
    'Wear socks on your hands for the next 10 minutes.', 'Try to say the alphabet backwards.',
    'Send a voice note of you beatboxing.', 'Post a picture of an embarrassing outfit you used to wear.',
    'Let someone in the server give you a new nickname.', 'Send a voice note of you singing a nursery rhyme.',
    'Do 15 sit-ups.', 'Try to breakdance.',
    'Send a message to your parents saying you are adopting a pet monkey.', 'Put a piece of tape on your nose for 5 minutes.',
    'Send a voice note of you trying to speak an alien language.', 'Post a screenshot of your most used apps.',
    'Let another player dare you to do something of their choice.', 'Do a wall sit for 1 minute.',
    'Send a picture of your messy room (if it is messy).', 'Try to whistle a song.',
    'Send a voice note of you acting like a robot.', 'Post a screenshot of your search history.',
    'Do your best impression of a teacher.', 'Send a message to a random person saying "I am an alien."',
    'Wear a hat backward for the next 15 minutes.', 'Try to say a tongue twister 3 times fast.',
    'Send a voice note of you acting like a pirate.', 'Post a picture of a childhood toy.',
    'Let someone in the server ask you a trivia question.', 'Do 20 squats.',
    'Send a message to your sibling (or friend) saying you are moving to Antarctica.', 'Put a book on your head and walk around for 1 minute.',
    'Send a voice note of you acting like a ghost.', 'Post a screenshot of your Spotify/Apple Music history.',
    'Let another player choose a word you must use in every sentence for the next 10 minutes.', 'Do a handstand (or try to).',
    'Send a picture of your pet (or a random animal if you dont have one).', 'Try to snap with both hands at the same time.',
    'Send a voice note of you acting like a zombie.', 'Post a screenshot of your home screen.',
    'Do your best impression of a superhero.', 'Send a message to a random person saying "I am a time traveler."',
    'Wear sunglasses indoors for the next 20 minutes.', 'Try to say the alphabet without moving your lips.',
    'Send a voice note of you acting like a dinosaur.', 'Post a picture of a drawing you made.',
    'Let someone in the server give you a math problem to solve.', 'Do 10 lunges.',
    'Send a message to your friend saying you are a secret agent.', 'Put a sticker on your forehead for 10 minutes.',
    'Send a voice note of you acting like a ninja.', 'Post a screenshot of your lock screen.',
    'Let another player tell you a joke and you cant laugh.', 'Do a cartwheel (or try to).',
    'Send a picture of your favorite mug.', 'Try to touch your toes without bending your knees.'
]
