MORE_TRUTHS = [
    'What is your biggest fear?', 'Have you ever cheated on a test?', 'What is the most embarrassing thing you have ever done?',
    'What is a secret you have never told anyone?', 'Who was your first crush?', 'Have you ever lied to your parents?',
    'What is the worst trouble you have ever been in?', 'If you could be invisible for a day, what would you do?',
    'What is a habit you have that you think is completely gross?', 'What is the longest you have gone without showering?',
    'Have you ever broken something and blamed someone else?', 'If you had to kiss one person in this server, who would it be?',
    'What is the most embarrassing message you have accidentally sent to the wrong person?', 'Have you ever been caught picking your nose?',
    'What is your weirdest flex?', 'What is the most awkward date you have ever been on?', 'Have you ever stolen anything?',
    'What is the biggest lie you have ever told?', 'Have you ever ghosted someone?', 'What is your most embarrassing nickname?',
    'What is the weirdest dream you have ever had?', 'Who do you secretly stalk on social media?', 'Have you ever pretended to be sick to get out of something?',
    'What is the most childish thing you still do?', 'Have you ever eavesdropped on a conversation?', 'What is the dumbest thing you have done on a dare?',
    'Who is your secret idol?', 'What is the most cringe-worthy thing you have posted online?', 'Have you ever peed in a pool?',
    'What is the most ridiculous rumor you have heard about yourself?', 'Have you ever had a crush on a teacher?',
    'What is your guilty pleasure song?', 'What is the weirdest food combination you enjoy?', 'Have you ever lied about your age?',
    'What is the most embarrassing thing your parents have caught you doing?', 'Have you ever ruined a surprise party?',
    'What is the worst gift you have ever received and pretended to like?', 'Have you ever worn the same underwear two days in a row?',
    'What is the most embarrassing thing you have searched for on Google?', 'Have you ever fallen asleep in public?',
    'What is the worst haircut you have ever had?', 'Have you ever tripped and fallen in front of a crowd?',
    'What is the most embarrassing thing you have done while sleepwalking?', 'Have you ever forgotten someones name immediately after they introduced themselves?',
    'What is the weirdest thing you do when you are alone?', 'Have you ever practiced kissing in the mirror?',
    'What is the most embarrassing thing you have said to a crush?', 'Have you ever laughed so hard you snorted?',
    'What is the worst advice you have ever given someone?', 'Have you ever accidentally liked an old photo while stalking someone on Instagram?',
    'What is the most embarrassing thing you have done in a video game?', 'Have you ever cried during a movie? Which one?',
    'What is the weirdest thing you have bought online?', 'Have you ever been caught talking to yourself?',
    'What is the most embarrassing thing you have worn?', 'Have you ever accidentally spit on someone while talking?',
    'What is the worst joke you have ever told that nobody laughed at?', 'Have you ever tripped over nothing?',
    'What is the most embarrassing thing you have done on a Zoom call?', 'Have you ever sent a text to the person it was about?',
    'What is the weirdest rumor you have believed?', 'Have you ever been caught picking a wedgie?',
    'What is the most embarrassing thing you have done at a party?', 'Have you ever pretended to know a language you dont?',
    'What is the worst excuse you have used to cancel plans?', 'Have you ever accidentally insulted someone to their face?',
    'What is the most embarrassing thing you have done while trying to impress someone?', 'Have you ever waved at someone who wasnt waving at you?',
    'What is the weirdest thing you have eaten?', 'Have you ever been caught singing in the shower?',
    'What is the most embarrassing thing you have done at the gym?', 'Have you ever forgotten where you parked your car?',
    'What is the worst injury you have gotten from doing something stupid?', 'Have you ever been caught taking a selfie?',
    'What is the most embarrassing thing you have done on public transportation?', 'Have you ever accidentally sent a romantic text to a family member?',
    'What is the weirdest thing you are afraid of?', 'Have you ever been caught stalking someone online?',
    'What is the most embarrassing thing you have done while drunk (if applicable)?', 'Have you ever accidentally walked into the wrong restroom?',
    'What is the worst mistake you have made at work/school?', 'Have you ever been caught picking your teeth?',
    'What is the most embarrassing thing you have done while dancing?', 'Have you ever accidentally said "I love you" to someone you shouldnt have?',
    'What is the weirdest thing you have found in your food?', 'Have you ever been caught checking yourself out in a window?',
    'What is the most embarrassing thing you have done in a group chat?', 'Have you ever accidentally sent a screenshot to the person you screenshotted?',
    'What is the worst thing you have cooked?', 'Have you ever been caught smelling your own armpits?',
    'What is the most embarrassing thing you have done while trying to be cool?', 'Have you ever accidentally called your teacher "Mom" or "Dad"?',
    'What is the weirdest thing you have done to get someones attention?', 'Have you ever been caught picking a scab?',
    'What is the most embarrassing thing you have done while singing karaoke?', 'Have you ever accidentally sent a voice note you didnt mean to?',
    'What is the worst thing you have done out of anger?', 'Have you ever been caught looking at inappropriate content?',
    'What is the most embarrassing thing you have done in front of a mirror?', 'Have you ever accidentally liked a post from years ago?'
]

MORE_DARES = [
    'Send a voice message of you singing the chorus of your favorite song.', 'Type a message using only your nose.',
    'Send the most embarrassing photo in your camera roll.', 'Change your Discord nickname to something silly for the next 10 minutes.',
    'Write a 3-line poem about the server owner.', 'Send a message to your crush saying "I love you" (or a friend if you dont have one).',
    'Act like a dog for your next 3 messages.', 'Post a selfie with a funny face.',
    'Confess something embarrassing you did today.', 'Give a random server member a compliment.',
    'Speak in Shakespearean English for the next 5 minutes.', 'Spam 5 random emojis in the chat.',
    'Tell a joke. If no one laughs, you have to do another dare.', 'Send your most recently used emoji 10 times.',
    'Change your profile picture to a meme for the rest of the day.', 'Do 10 pushups and send a video (or just say you did them).',
    'Drink a glass of water without using your hands.', 'Eat a spoonful of hot sauce (or mustard/ketchup).',
    'Call a random friend and sing "Happy Birthday" to them.', 'Do your best impression of a famous celebrity.',
    'Balance a spoon on your nose for 10 seconds.', 'Draw a picture blindfolded and share it.',
    'Text your mom "I just got married!" and share her response.', 'Do a silly dance for 30 seconds.',
    'Eat a raw piece of onion or garlic.', 'Talk with a fake accent for the next 10 minutes.',
    'Let someone in the server choose your next avatar.', 'Send a voice note of you doing an evil laugh.',
    'Write a love letter to your favorite food.', 'Do 20 jumping jacks.',
    'Try to lick your elbow.', 'Post a screenshot of your YouTube watch history.',
    'Send a voice note of you trying to rap.', 'Make a funny face and keep it that way for 2 minutes.',
    'Talk in the third person for the next 15 minutes.', 'Send a message to your best friend saying you are mad at them (and then say its a dare).',
    'Put an ice cube down your shirt and leave it there until it melts.', 'Try to juggle 3 items of your choice.',
    'Send a voice note of you making animal noises.', 'Write a short story using only emojis.',
    'Let another player ask you a question that you must answer truthfully.', 'Do a plank for 1 minute.',
    'Send a picture of the inside of your fridge.', 'Try to touch your nose with your tongue.',
    'Send a voice note of you whispering a secret.', 'Post a screenshot of your recent emojis.',
    'Do your best impression of another server member.', 'Send a message to a random person saying "I know what you did."',
    'Wear socks on your hands for the next 10 minutes.', 'Try to say the alphabet backwards.',
    'Send a voice note of you beatboxing.', 'Post a picture of an embarrassing outfit you used to wear.',
    'Let someone in the server give you a new nickname.', 'Send a voice note of you singing a nursery rhyme.',
    'Do 15 sit-ups.', 'Try to breakdance.',
    'Send a message to your parents saying you are adopting a pet monkey.', 'Put a piece of tape on your nose for 5 minutes.',
    'Send a voice note of you trying to speak an alien language.', 'Post a screenshot of your most used apps.',
    'Let another player dare you to do something of their choice.', 'Do a wall sit for 1 minute.',
    'Send a picture of your messy room (if it is messy).', 'Try to whistle a song.',
    'Send a voice note of you acting like a robot.', 'Post a screenshot of your search history.',
    'Do your best impression of a teacher.', 'Send a message to a random person saying "I am an alien."',
    'Wear a hat backward for the next 15 minutes.', 'Try to say a tongue twister 3 times fast.',
    'Send a voice note of you acting like a pirate.', 'Post a picture of a childhood toy.',
    'Let someone in the server ask you a trivia question.', 'Do 20 squats.',
    'Send a message to your sibling (or friend) saying you are moving to Antarctica.', 'Put a book on your head and walk around for 1 minute.',
    'Send a voice note of you acting like a ghost.', 'Post a screenshot of your Spotify/Apple Music history.',
    'Let another player choose a word you must use in every sentence for the next 10 minutes.', 'Do a handstand (or try to).',
    'Send a picture of your pet (or a random animal if you dont have one).', 'Try to snap with both hands at the same time.',
    'Send a voice note of you acting like a zombie.', 'Post a screenshot of your home screen.',
    'Do your best impression of a superhero.', 'Send a message to a random person saying "I am a time traveler."',
    'Wear sunglasses indoors for the next 20 minutes.', 'Try to say the alphabet without moving your lips.',
    'Send a voice note of you acting like a dinosaur.', 'Post a picture of a drawing you made.',
    'Let someone in the server give you a math problem to solve.', 'Do 10 lunges.',
    'Send a message to your friend saying you are a secret agent.', 'Put a sticker on your forehead for 10 minutes.',
    'Send a voice note of you acting like a ninja.', 'Post a screenshot of your lock screen.',
    'Let another player tell you a joke and you cant laugh.', 'Do a cartwheel (or try to).',
    'Send a picture of your favorite mug.', 'Try to touch your toes without bending your knees.'
]


# Extended Truths
MORE_TRUTHS.extend([
    'What is your most toxic trait?', 'Have you ever skipped school/work to do nothing?', 'What is the most awkward text you have received?',
    'What is your most embarrassing childhood memory?', 'Have you ever snooped through someones phone?', 'Who is your least favorite person in this server?',
    'What is a controversial opinion you hold?', 'Have you ever peed in the shower?', 'What is the worst lie you told to get out of a date?',
    'What is your biggest regret?', 'Have you ever shoplifted?', 'What is a secret you kept from your best friend?',
    'What is the strangest thing you find attractive?', 'Have you ever had a crush on a fictional character?', 'What is the most awkward thing you have done on a date?',
    'What is the worst habit you cant break?', 'Have you ever lied about your skills on a resume?', 'What is your most irrational fear?',
    'Have you ever practiced an argument in the mirror?', 'What is the most embarrassing thing you have worn in public?',
    'What is the worst text you sent to the wrong person?', 'Have you ever cried to get out of trouble?', 'What is a movie you secretly hate but pretend to love?',
    'What is the most embarrassing thing in your search history right now?', 'Have you ever had a crush on a friends sibling?',
    'What is your weirdest flex?', 'What is the most inappropriate time you burst out laughing?', 'Have you ever eaten something off the floor?',
    'Have you ever pretended to be someone else online?', 'What is the most embarrassing thing you did for a crush?',
    'What is the weirdest rumor you heard about yourself?', 'What is a lie you told that spiraled out of control?', 'Have you ever stalked an ex online?',
    'What is the most embarrassing thing you have done while drunk?', 'What is the worst gift you ever gave someone?',
    'Have you ever stolen money from a family member?', 'What is a song you are embarrassed to know all the lyrics to?',
    'What is the most awkward interaction you had with a teacher?', 'Have you ever dropped your phone in the toilet?', 'What is the worst hairstyle you ever had?',
    'What is the weirdest thing you do in the shower?', 'Have you ever regifted a present?', 'What is the most embarrassing thing your parents caught you doing?',
    'What is a secret talent you have that you are embarrassed about?', 'Have you ever sent a dirty text to the wrong person?',
    'What is the longest you have gone without brushing your teeth?', 'What is the most awkward encounter you have had with a stranger?',
    'Have you ever lied about your age to get something?', 'What is the most embarrassing phase you went through?',
    'What is the weirdest food you have ever craved?', 'Have you ever ruined someones relationship?', 'What is the most awkward moment you had at a family gathering?',
    'What is a lie you still maintain to this day?', 'Have you ever accidentally liked an exs post from years ago?',
    'What is the most embarrassing thing you have done for money?', 'What is the weirdest dream you remember vividly?',
    'Have you ever been rejected publicly?', 'What is the worst thing you have said behind a friends back?',
    'What is a secret you would never tell your parents?', 'Have you ever cheated in a game and still lost?',
    'What is the most embarrassing video of you that exists?', 'Have you ever faked an illness to stay home?',
    'What is the most cringe-worthy pickup line you have used?', 'Have you ever been caught picking your nose in traffic?',
    'What is the most awkward silence you have ever experienced?', 'Have you ever laughed at something you shouldnt have?',
    'What is the weirdest thing you have searched for on YouTube?', 'Have you ever lied about watching a popular show?',
    'What is the most embarrassing thing you did to fit in?', 'What is the most childish thing you still enjoy?',
    'Have you ever accidentally called a teacher Mom?', 'What is the worst excuse you gave for being late?',
    'What is the most awkward thing you have done in a job interview?', 'Have you ever pretended not to see someone to avoid talking to them?',
    'What is the weirdest thing you have ever collected?', 'Have you ever eaten someone elses food from the fridge at work/school?',
    'What is the most embarrassing thing you have done in front of a mirror?', 'Have you ever lied to get a discount?',
    'What is the most awkward thing you have done while trying to be cool?', 'Have you ever accidentally sent a voice note you meant to delete?',
    'What is the weirdest habit you have when you are nervous?', 'Have you ever pretended to be on the phone to avoid someone?',
    'What is the most embarrassing thing you have done on social media?', 'Have you ever accidentally liked a message instead of replying?',
    'What is the worst thing you have ever tasted?', 'Have you ever been caught taking a selfie in public?',
    'What is the most awkward thing you have done in a group chat?', 'Have you ever sent a text complaining about someone to that person?',
    'What is the weirdest thing you have ever believed as a child?', 'Have you ever been caught staring at someone?',
    'What is the most embarrassing thing you have done while singing in the car?', 'Have you ever accidentally spit while talking to a crush?',
    'What is the worst advice you have ever followed?', 'Have you ever been caught talking to yourself in public?',
    'What is the most awkward thing you have done while trying to flirt?', 'Have you ever accidentally worn your clothes inside out?',
    'What is the weirdest thing you have ever googled at 3 AM?', 'Have you ever been caught smelling your own breath?',
    'What is the most embarrassing thing you have done while trying to impress a friend?', 'Have you ever accidentally sent a screenshot of a chat back to the same chat?'
])

# Extended Dares
MORE_DARES.extend([
    'Call a random contact and sing Let It Go.', 'Let another player tweet something from your account.',
    'Do 50 squats while shouting I love fitness!.', 'Eat a spoonful of plain mustard.',
    'Send a message to your crush saying you had a dream about them.', 'Let someone draw on your face with a marker.',
    'Do the Macarena dance for 1 minute and record it.', 'Eat a slice of lemon without making a face.',
    'Text your mom that you are dropping out of school/work to become a professional clown.', 'Let another player style your hair.',
    'Do a plank for 2 minutes while singing the alphabet.', 'Eat a raw egg.',
    'Send a voice note of you barking like a dog for 30 seconds.', 'Let someone post an embarrassing photo on your Instagram story.',
    'Do 20 burpees while reciting your favorite poem.', 'Eat a spoonful of hot sauce.',
    'Text your ex saying I miss you.', 'Let another player choose your outfit for tomorrow.',
    'Do a headstand for 30 seconds.', 'Eat a spoonful of mayonnaise.',
    'Send a video of you doing the worm dance.', 'Let someone write a word on your forehead.',
    'Do 30 pushups while singing Baby Shark.', 'Drink a raw egg mixed with milk.',
    'Text your boss/teacher a meme without context.', 'Let another player control your phone for 1 minute.',
    'Do a cartwheel and record it.', 'Eat a piece of dog/cat food (or a plain cracker if you dont have pets).',
    'Send a voice note of you crying like a baby.', 'Let someone tickle you for 30 seconds.',
    'Do 50 jumping jacks while holding your breath.', 'Eat a spoonful of plain butter.',
    'Text a random number I know your secret.', 'Let another player do your makeup.',
    'Do a handstand and hold it as long as you can.', 'Eat a slice of raw onion.',
    'Send a video of you acting like a monkey.', 'Let someone slap you (gently) on the cheek.',
    'Do 20 lunges while carrying a heavy object.', 'Drink a shot of vinegar.',
    'Text your best friend We need to talk and dont reply for an hour.', 'Let another player paint your nails.',
    'Do a backflip (or try to).', 'Eat a spoonful of salt.',
    'Send a voice note of you screaming as loud as you can.', 'Let someone blindfold you and feed you something.',
    'Do 10 pull-ups (or try to).', 'Drink a shot of pickle juice.',
    'Text your parents I got arrested.', 'Let another player choose your profile picture for a day.',
    'Do a split (or try to).', 'Eat a spoonful of plain flour.',
    'Send a video of you doing an interpretive dance.', 'Let someone ice your back.',
    'Do 50 crunches while singing a lullaby.', 'Drink a shot of soy sauce.',
    'Text your sibling I broke your favorite thing.', 'Let another player send a text from your phone.',
    'Do a bridge for 1 minute.', 'Eat a spoonful of plain sugar.',
    'Send a voice note of you laughing uncontrollably.', 'Let someone draw a mustache on your face.',
    'Do 20 high knees while yelling I am the champion!.', 'Drink a glass of water with salt in it.',
    'Text your crush a weird pickup line.', 'Let another player choose a song you must listen to on repeat for 10 minutes.',
    'Do a somersault and record it.', 'Eat a spoonful of plain coffee powder.',
    'Send a video of you acting like a robot.', 'Let someone pour cold water on your head.',
    'Do 30 calf raises while holding a book on your head.', 'Drink a glass of milk with pepper in it.',
    'Text your friend a random quote from a movie.', 'Let another player choose a word you must say in every sentence.',
    'Do a frog jump across the room.', 'Eat a spoonful of plain cocoa powder.',
    'Send a voice note of you speaking gibberish.', 'Let someone wrap you in toilet paper like a mummy.',
    'Do 20 sit-ups while clapping your hands.', 'Drink a glass of water with lemon and salt.',
    'Text your mom What is for dinner? 10 times in a row.', 'Let another player choose a weird filter for your next selfie.',
    'Do a duck walk across the room.', 'Eat a spoonful of plain cinnamon (be careful!).',
    'Send a video of you trying to juggle.', 'Let someone put a sticker on your face.',
    'Do 10 burpees while singing a rap song.', 'Drink a glass of water with a dash of hot sauce.',
    'Text your friend a picture of a random object and say This reminds me of you.', 'Let another player choose a weird fact you must share.',
    'Do a crab walk across the room.', 'Eat a spoonful of plain peanut butter.',
    'Send a voice note of you trying to beatbox.', 'Let someone put a funny hat on you.',
    'Do 20 jumping jacks while reciting the alphabet backwards.', 'Drink a glass of water with a dash of vinegar.',
    'Text your friend a joke that makes no sense.', 'Let another player choose a weird animal sound you must make.',
    'Do a bear crawl across the room.', 'Eat a spoonful of plain jelly.',
    'Send a video of you trying to do magic.', 'Let someone put a funny pair of glasses on you.',
    'Do 10 lunges while singing an opera song.', 'Drink a glass of water with a dash of soy sauce.',
    'Text your friend a random emoji and say This is my current mood.', 'Let another player choose a weird dance move you must do.'
])
