# cogs/fun_roast.py
import discord
from discord.ext import commands
import random

import typing

class FunRoast(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.roasts = [
            "Bhai, teri shakal dekh kar lagta hai ki jab bhagwan dimaag baant rahe the, tab tu SRM ke bhandare me khana kha raha tha!",
            "Shauk toh bade bade hain par halat aisi hai ki market me 'Vim Bar' bhi EMI par lena pad jaye.",
            "Tujhse zyada dhyan toh log YouTube ke ads par deh rahe hain aaj kal.",
            "Tera dimaag ekdum naya hai, bilkul brand new... Kyunki tumne use kabhi khol kar use hi nahi kiya!",
            "Bhai tere se acche expressions toh thermal engineering ki boring classes me aa jaate hain.",
            "Tu itna bada loser hai ki agar koi 'Failure Competition' ho, toh tu usme bhi 2nd aayega!",
            "Bhai, teri baatein sun kar dimaag ke cells suicide kar lete hain.",
            "Teri shakal par sirf tera baap hi has sakta hai, wo bhi afsos ke sath.",
            "Agar dimaag bechne niklega na, toh 'Unused Condition' bol kar sabse zyada rate tera hi lagega.",
            "Tu wo naseebwala insaan hai jise dekh kar bhoot bhi apna rasta badal leta hai.",
            "Bhai, thoda dimaag coding me laga leta toh aaj bot chalane ki jagah khud koi dhasu startup chala raha hota.",
            "Teri har baat sunkar aisa lagta hai jaise kisi ne dimaag par slow-mode laga diya ho.",
            "Tu jahan khada hota hai na, wahan ki hawa bhi apna direction badal leti hai.",
            "Tera dimaag aur tera bank balance, dono ek doosre ko competition de rahe hain ki kaun pehle zero hoga.",
            "Bhai, teri personality dekh kar lagta hai ki tujhe 'Error 404' ne janam diya hai.",
            "Tere jaisa dimaag agar scientist ke paas hota, toh aaj hum chand ki jagah kachre ke dher par baithe hote.",
            "Tujhe dekh kar lagta hai ki bhagwan ne tujhe bina kisi blueprint ke hi tayaar kar diya.",
            "Teri dosti aur teri coding, dono par koi ek minute se zyada bharosa nahi kar sakta.",
            "Tu wo legend hai jo online class me bhi peeche ki seat dhoodhta hai.",
            "Bhai, teri baaton me itna darr hai jaise semester exam ke ek raat pehle ka syllabus.",
            "Tu dosto ke beech utna hi useful hai jitna bada laptop me internet explorer hota hai.",
            "Teri shakal par kisi ne 'Ctrl+Z' dabane ki koshish ki thi par lagta hai command beech me hi crash ho gaya.",
            "Bhai, tujhse zyada speed toh college ke low-end Wi-Fi me hoti hai.",
            "Tera dimaag dekh kar lagta hai ki usme hamesha buffering hi chalti rehti hai.",
            "Tu jahan jaata hai, wahan ka josh automatic dnd (do not disturb) status par chala jaata hai.",
            "Bhai, tujhe dimaag ki jagah bhagwan ne galti se kachra-box assign kar diya tha.",
            "Tu itna bada khiladi hai ki ludo me bhi tera token pehle ghar se nikalne se mana kar deta hai.",
            "Teri har baat sunkar lagta hai jaise koi purana system bina graphics card ke heavy game chala raha ho.",
            "Bhai, tere se bade roasts toh dosto ke group chat me bina bot ke hi thuk jaate hain.",
            "Tu wo insaan hai jo calculator me bhi 2+2 check karne ke liye do baar sochta hai.",
            "Bhai teri life ka scale ekdum khali database jaisa hai, jisme koi table hi nahi mili.",
            "Tujhe dekh kar lagta hai ki nature ne tere upar apna poora experiment fail kar diya.",
            "Bhai, tere bolne se pehle tera dimaag hamesha 'Not Responding' dikha deta hai.",
            "Tu server me utna hi akela hai jitna engineering me ladkiyaan hoti hain.",
            "Bhai, tujhse bade logic toh bot ke crash errors me mil jaate hain.",
            "Tera dimaag ekdum cloud jaisa hai... Hamesha khali aur hawa me udta rehta hai!",
            "Bhai tere paas dimaag itna hi hai jitna Lays ke packet me chips.",
            "Tu wo dost hai jiska hotspot use karne me bhi sharam aati hai, speed hi nahi milti.",
            "Teri kismat itni kharab hai ki 'buy 1 get 1 free' me bhi tujhe sirf bill pakda dete hain.",
            "Tere jaisa zero confidence toh mere purane phone ki battery ka bhi nahi hai.",
            "Bhai, tujhe dekh kar lagta hai ki god ne tujhe rough draft me hi chhod diya.",
            "Tera rizz itna minus me hai ki ladkiyan tujhe dekh kar apna gender question kar leti hain.",
            "Tu exam me itna blank hota hai jitna mere bank account ka balance.",
            "Bhai, tujhe ignore karna utna hi aasaan hai jitna YouTube ke unskippable ads ke baad ka skip button.",
            "Tera existence mere liye 'Terms and Conditions' jaisa hai, sab jante hain par koi dhyan nahi deta.",
            "Bhai teri shakal itni common hai ki log tujhe dekh kar sochte hain, 'Ye kiska delivery boy hai?'",
            "Agar bevkufi ki koi crypto hoti, toh aaj tu Elon Musk ko takkar de raha hota.",
            "Teri baatein aisi hoti hain jaise bina masala wali maggi, kisi ko pasand nahi aati.",
            "Tu itna useless hai ki mosquito bhi tujhe kaatne se pehle do baar sochta hai ki khoon me error na mil jaye.",
            "Bhai tujhe insult karna bhi waste of time lagta hai, nature ne already apna kaam kar diya hai.",
            "Tere aane se mehfil me utni hi rounaq aati hai jitni Monday morning ki class me.",
            "Tu wo tab hai browser ka jo galti se khul jata hai aur turant close kar diya jata hai.",
            "Bhai teri personality utni hi dull hai jitna bina dark mode ka discord.",
            "Agar tu ek code hota toh tujhe sirf 'IndexError: out of range' milta zindagi bhar.",
            "Tu woh insaan hai jiske memes par bhi log 'haha' react karne me aalas karte hain.",
            "Bhai teri life me progress utni hi dikhti hai jitni Windows update ki loading screen me.",
            "Tujhse baat karke lagta hai ki main apna IQ zameen par ragad raha hoon.",
            "Tera dimaag airplane mode me paida hua tha aur lagta hai abhi tak switch off nahi hua.",
            "Bhai teri shakal dekh kar toh 'Face ID' bhi lock ho kar password maangne lagti hai.",
            "Tu wo ekmatra banda hai jise friendzone karne me bhi ladkiyo ko sharam aati hai.",
            "Agar aalsi logo ka koi olympics hota, toh tu usme participate karne me bhi aalas kar jata.",
            "Tere se acchi vibes toh Monday ke 9 AM lecture se aati hai.",
            "Tu wo banda hai jo group photo me hamesha aadha cut jata hai aur kisi ko farq nahi padta.",
            "Bhai tu itna bhulakkad hai ki bhagwan tujhe good looks dena bhi bhool gaye.",
            "Teri zindagi ek infinite loop jaisi hai, chal rahi hai par kahin pohoch nahi rahi.",
            "Tera sense of humor utna hi thanda hai jitna dhabe ka baasi samosa.",
            "Bhai teri baaton ka koi sense nahi banta, bilkul kisi third-grade b-grade movie ki tarah.",
            "Tu wo free ka dhaniya hai jo sabzi wala bhi ab muh bana kar deta hai.",
            "Tere paas dimaag hota toh tujhe realize hota ki tera paida hona ek typo tha.",
            "Bhai teri aur meri dosti bilkul Wi-Fi jaisi hai, jab tu paas hota hai connection slow ho jata hai.",
            "Agar stupidity ka koi patent hota, toh tera naam sabse upar likha hota bhai.",
            "Tu wo character hai movie ka jo pehle 5 minute me hi marr jata hai aur koi dhyan nahi deta.",
            "Teri shakal me utna hi filter chahiye hota hai jitna Instagram ke naye update me bhi nahi hai.",
            "Bhai, teri logic sunkar Newton bhi apni kabr me do baar paltiya khaa gaya hoga.",
            "Tera confidence itna over hai ki tujhe lagta hai tera code bina bug ke ek baar me run hoga.",
            "Tu wo message hai jise padh kar log 'seen' par chhod dena better samajhte hain.",
            "Bhai tera aura itna minus me hai ki bhoot bhi tujhse dar kar door bhagte hain.",
            "Tere muh se nikli har baat 'NullPointerException' ki tarah dimaag kharab karti hai.",
            "Tu zindagi me bas wahi ek bug hai jise koi fix nahi karna chahta, bas ignore kar dete hain.",
            "Teri value utni hi hai jitni gta vice city me traffic rules ki hoti thi.",
            "Bhai teri life ekdum buffering video ki tarah hai, frustrate karti hai aur aage badhti hi nahi.",
            "Tu wo question paper ka aakhiri sawal hai jise sab chhod dete hain.",
            "Tera attitude bilkul dial-up connection jaisa hai, bahut awaaz karta hai par output kuch nahi.",
            "Bhai tu paida hua tha ya kisi ne galti se 'Ctrl+V' daba diya tha kachre me?",
            "Teri shakal dekh ke toh 'captchas' bhi verify nahi kar paate ki tu human hai ya nahi.",
            "Tu wo banda hai jo 'Hello World' print karne ke baad apne aap ko hacker samajhta hai.",
            "Bhai tere aane se chat dead ho jati hai, tu literal conversation killer hai.",
            "Teri zindagi ek fail test case ki tarah hai, kabhi pass hone ki umeed hi nahi hai.",
            "Tu utna hi relevant hai jitna aaj ke zamane me Orkut.",
            "Tera sense of dressing utna hi outdated hai jitna internet explorer ka home page.",
            "Bhai tere dimaag ke server pe lagta hai hamesha DDoS attack chalta rehta hai.",
            "Tu wo dost hai jise party me sirf isliye bulate hain taaki bill divide ho sake.",
            "Teri life ki problem resolving skill utni hi kharab hai jitni Indian customer care ki.",
            "Bhai tujhe dekh kar lagta hai teri creation ke waqt bhagwan break par chale gaye the.",
            "Tera confidence dekh kar mujhe hansi nahi, taras aata hai bhai.",
            "Tu wo pop-up ad hai jise sabse pehle close karne ka man karta hai.",
            "Bhai tere paas aisi koi skill nahi hai jiske liye log tujhe seriously lein.",
            "Tera dimaag utna hi smooth hai jitna kachha rasta barsaat me.",
            "Tu zindagi ka wo feature hai jo kisi release notes me mention karne layaq nahi hai.",
            "Bhai, teri shakal ek failed API request ki tarah 404 Not Found feel deti hai.",
            "Teri aukaat utni hi hai jitni shaadi me paneer khatam hone ke baad sabzi ki hoti hai.",
            "Tu wo file hai jise delete karte waqt warning tak nahi aati.",
            "Bhai tera dimaag default settings par set hai, aur updates hamesha fail ho jate hain.",
            "Tu wo joke hai jo kisi ko samajh nahi aata aur tujhe khud explain karna padta hai.",
            "Tera presence room me utna hi noticeable hai jitna terms & conditions ka text.",
            "Bhai tere paas options utne hi kam hain jitne apple ecosystem me customisation ke hote hain.",
            "Tu wo playlist hai jise koi sunna pasand nahi karta, bas shuffle pe padi rehti hai.",
            "Teri baaton me utna hi wazan hai jitna Lays ke packet ki hawa me.",
            "Bhai tujhe toh aliens bhi kidnap karne ke baad agle hi din dharti par wapas drop kar denge.",
            "Tu wo dost hai jo hamesha udhaar mangta hai par lautate waqt amnesia ka shikar ho jata hai.",
            "Teri existence ek deprecated function ki tarah hai, ab kisi kaam ki nahi rahi.",
            "Bhai tere paas utna hi rizz hai jitna ek pathar me emotion hota hai.",
            "Tu wo group member hai jo assignment me kuch nahi karta par naam sabse upar chahta hai.",
            "Teri life ka map utna hi confusing hai jitna ladkiyon ka 'I am fine'.",
            "Bhai tera dimaag lagta hai 'Read Only' mode par stuck ho gaya hai.",
            "Tu wo notification hai jise phone me hamesha 'clear all' kar diya jata hai.",
            "Teri shakal dekh ke pados ke kutte bhi sochte hain, 'Bhai, main toh theek hi dikhta hoon'.",
            "Bhai tu wo error hai jise ignore karke developer aage badh jata hai.",
            "Tera logic utna hi flawed hai jitna horror movies me akele basement me jana.",
            "Tu wo insaan hai jise dekh kar khud motivation bhi demotivate ho jati hai.",
            "Bhai teri personality utni hi fake hai jitni online aane wale ads me ladkiyan.",
            "Tera future utna hi andhkar me hai jitna bina light ke dark room.",
            "Tu wo banda hai jiska chat GPT bhi reply dene se pehle do baar thak jata hai.",
            "Bhai tera IQ room temperature se bhi neeche gir gaya hai lagta hai.",
            "Tu utna hi useless hai jitna 'T' tsunami me.",
            "Teri zindagi ek aisi book hai jise kholte hi neend aa jati hai.",
            "Bhai tujhse dosti karna aisi galti hai jo main apne dushmano ko bhi recommend na karu.",
            "Tu wo password hai jo itna weak hota hai ki system khud reject kar deta hai.",
            "Tera dimaag utna hi processing power rakhta hai jitna purane zamane ka calculator.",
            "Bhai teri shakal toh zoom karne par bhi pixelated hi lagti hai.",
            "Tu wo banda hai jo pizza me ananas dalne walo se bhi zyada nafrat ke kabil hai.",
            "Tera attitude aise hai jaise tu CEO hai, par harkatein ekdum intern wali hain.",
            "Bhai teri existence nature ka sabse bada bug hai, jiska koi patch nahi aaya ab tak.",
            "Tu wo spam mail hai jo seedha junk folder me jata hai aur kabhi khola nahi jata.",
            "Tera humor utna hi dry hai jitna 5 din purana bread.",
            "Bhai tu aisi kadi hai chain ki jo kisi se nahi judti, bas beech me latki rehti hai."
        ]

    @commands.hybrid_command(name="roast")
    async def roast(self, ctx, member: discord.Member = None):
        """Kisi ki dosto ke beech witty Hinglish roasts ke sath taang kheenchte hain."""
        member = member or ctx.author
        
        # UNO reverse if the target is the bot owner or their name contains 'rishav'
        if member.id in self.bot.owner_ids or "rishav" in member.display_name.lower() or "rishav" in member.name.lower():
            member = ctx.author
            
        roast_text = random.choice(self.roasts)
        await ctx.send(f"🔥 {member.mention}, {roast_text}")

async def setup(bot):
    await bot.add_cog(FunRoast(bot))